import { Atividade } from '@app/model/atividade';
import { Equipe } from '@app/model/equipe';
import { AtividadeService } from '@app/services/atividade.service';

export const importedData: {
  rodada: number;
  grupo: number;
  matricula: number;
  nome: string;
}[] = [
  {
    rodada: 0,
    grupo: 1,
    matricula: 2478,
    nome: 'Bianca De Oliveira Brecailo',
  },
  {
    rodada: 0,
    grupo: 1,
    matricula: 2370,
    nome: 'Djenifer Renata Pereira',
  },
  {
    rodada: 0,
    grupo: 1,
    matricula: 2408,
    nome: 'Gabriele Batista Do Nascimento',
  },
  {
    rodada: 0,
    grupo: 2,
    matricula: 2376,
    nome: 'Samuel Eberhardt',
  },
  {
    rodada: 0,
    grupo: 2,
    matricula: 2469,
    nome: 'Lucas Yoshio Nakano',
  },
  {
    rodada: 0,
    grupo: 2,
    matricula: 2369,
    nome: 'Kauane Santana Da Rosa',
  },
  {
    rodada: 0,
    grupo: 2,
    matricula: 2436,
    nome: 'Maria Teresa Ferreira Lima De Almeida',
  },
  {
    rodada: 0,
    grupo: 3,
    matricula: 2450,
    nome: 'Henrique Castro Santos',
  },
  {
    rodada: 0,
    grupo: 3,
    matricula: 2520,
    nome: 'Leonardo Barbosa Burgomeister',
  },
  {
    rodada: 0,
    grupo: 3,
    matricula: 2434,
    nome: 'Ana Bittencourt Vidigal',
  },
  {
    rodada: 0,
    grupo: 3,
    matricula: 2457,
    nome: 'Alessandra Boscardin Aver',
  },
  {
    rodada: 0,
    grupo: 4,
    matricula: 2445,
    nome: 'Matheus Dos Santos Pedrozo De Lima',
  },
  {
    rodada: 0,
    grupo: 4,
    matricula: 2509,
    nome: 'Cesar André Costa Vaz',
  },
  {
    rodada: 0,
    grupo: 4,
    matricula: 2402,
    nome: 'Deborah Eberle Dos Santos',
  },
  {
    rodada: 0,
    grupo: 4,
    matricula: 2443,
    nome: 'Natalia Seixas Dias',
  },
  {
    rodada: 0,
    grupo: 5,
    matricula: 2465,
    nome: 'Matheus Henrique Tambosi',
  },
  {
    rodada: 0,
    grupo: 5,
    matricula: 2503,
    nome: 'Bernardo Dos Reis De Melo',
  },
  {
    rodada: 0,
    grupo: 5,
    matricula: 2368,
    nome: 'Bruna Naomi Yamanaka Silva',
  },
  {
    rodada: 0,
    grupo: 5,
    matricula: 2396,
    nome: 'Ana Paula Kessler Gonçalves',
  },
  {
    rodada: 0,
    grupo: 6,
    matricula: 2377,
    nome: 'Oswaldo Da Silva Schermach',
  },
  {
    rodada: 0,
    grupo: 6,
    matricula: 2510,
    nome: 'Julio Teixeira Bojan',
  },
  {
    rodada: 0,
    grupo: 6,
    matricula: 2371,
    nome: 'Andrea Alexandra Sánez Oquendo',
  },
  {
    rodada: 0,
    grupo: 6,
    matricula: 2438,
    nome: 'Yasmin Mayer',
  },
  {
    rodada: 0,
    grupo: 7,
    matricula: 2507,
    nome: 'Gustavo Kumasawa',
  },
  {
    rodada: 0,
    grupo: 7,
    matricula: 2430,
    nome: 'Larissa Paschoalin',
  },
  {
    rodada: 0,
    grupo: 7,
    matricula: 2384,
    nome: 'Gabriela Bogomolof Taquegami',
  },
  {
    rodada: 0,
    grupo: 7,
    matricula: 2511,
    nome: 'Herivelton José Gomes Da Trindade Júnior',
  },
  {
    rodada: 0,
    grupo: 8,
    matricula: 2422,
    nome: 'Raquel Daleffi Zocoler',
  },
  {
    rodada: 0,
    grupo: 8,
    matricula: 2518,
    nome: 'Frederico Westphalen Mendes Machado',
  },
  {
    rodada: 0,
    grupo: 8,
    matricula: 2473,
    nome: 'Laís Affornali Fernandes',
  },
  {
    rodada: 0,
    grupo: 8,
    matricula: 2426,
    nome: 'Matheus Teixeira Souza',
  },
  {
    rodada: 0,
    grupo: 9,
    matricula: 2464,
    nome: 'Isabela Martin Silva',
  },
  {
    rodada: 0,
    grupo: 9,
    matricula: 2383,
    nome: 'Alessandra Souza Da Silva',
  },
  {
    rodada: 0,
    grupo: 9,
    matricula: 2448,
    nome: 'Gabriel Vieira Rodrigues',
  },
  {
    rodada: 0,
    grupo: 9,
    matricula: 2497,
    nome: 'Pietro Ricardo Schoch Alves',
  },
  {
    rodada: 0,
    grupo: 10,
    matricula: 2413,
    nome: 'Letícia Camargo De Sá Silva',
  },
  {
    rodada: 0,
    grupo: 10,
    matricula: 2447,
    nome: 'Ana Luisa Duda Stege',
  },
  {
    rodada: 0,
    grupo: 10,
    matricula: 2390,
    nome: 'Marcus Augusto Ferreira Dudeque',
  },
  {
    rodada: 0,
    grupo: 10,
    matricula: 2526,
    nome: 'Guilerme Moreira Ribeiro Barciki',
  },
  {
    rodada: 0,
    grupo: 11,
    matricula: 2423,
    nome: 'Daniella Onishi',
  },
  {
    rodada: 0,
    grupo: 11,
    matricula: 2440,
    nome: 'Natália Grein Silva',
  },
  {
    rodada: 0,
    grupo: 11,
    matricula: 2409,
    nome: 'Alan Renato Bunese',
  },
  {
    rodada: 0,
    grupo: 11,
    matricula: 2463,
    nome: 'Francisco Lucas Rezende',
  },
  {
    rodada: 0,
    grupo: 12,
    matricula: 2381,
    nome: 'Melissa Fernanda Rodrigues Siqueira',
  },
  {
    rodada: 0,
    grupo: 12,
    matricula: 2442,
    nome: 'Isadora Rossetto Nogueira Drummond',
  },
  {
    rodada: 0,
    grupo: 12,
    matricula: 2485,
    nome: 'Gabriel Puppi Gozzo',
  },
  {
    rodada: 0,
    grupo: 12,
    matricula: 2397,
    nome: 'Eduardo Rosso Barbosa',
  },
  {
    rodada: 0,
    grupo: 13,
    matricula: 2412,
    nome: 'Jéssica Akemi Meguro',
  },
  {
    rodada: 0,
    grupo: 13,
    matricula: 2437,
    nome: 'Natalia Da Rosa',
  },
  {
    rodada: 0,
    grupo: 13,
    matricula: 2360,
    nome: 'Mario Morais Neto',
  },
  {
    rodada: 0,
    grupo: 13,
    matricula: 2350,
    nome: 'Alessandro Maciel Schmidt',
  },
  {
    rodada: 0,
    grupo: 14,
    matricula: 2406,
    nome: 'Helen Skorupski Sloboda',
  },
  {
    rodada: 0,
    grupo: 14,
    matricula: 2421,
    nome: 'Ianara De Souza Maldaner',
  },
  {
    rodada: 0,
    grupo: 14,
    matricula: 2481,
    nome: 'Bruno Yuiti Leão Imai',
  },
  {
    rodada: 0,
    grupo: 14,
    matricula: 2517,
    nome: 'Jean Ricardo Grein',
  },
  {
    rodada: 0,
    grupo: 15,
    matricula: 2439,
    nome: 'Jady Torralvo Alves',
  },
  {
    rodada: 0,
    grupo: 15,
    matricula: 2475,
    nome: 'Geovanna Kasemirinski Da Silva',
  },
  {
    rodada: 0,
    grupo: 15,
    matricula: 2407,
    nome: 'Bruno Siedekum Thuma',
  },
  {
    rodada: 0,
    grupo: 15,
    matricula: 2512,
    nome: 'Pablo Enrique Harbar Penas',
  },
  {
    rodada: 0,
    grupo: 16,
    matricula: 2395,
    nome: 'Giulia Andreazza Amaral',
  },
  {
    rodada: 0,
    grupo: 16,
    matricula: 2419,
    nome: 'Marina De Domenico Salioni Dubuc',
  },
  {
    rodada: 0,
    grupo: 16,
    matricula: 2496,
    nome: 'Vitor Aguiar Treglia',
  },
  {
    rodada: 0,
    grupo: 16,
    matricula: 2361,
    nome: 'Leonardo José Zanotti',
  },
  {
    rodada: 0,
    grupo: 17,
    matricula: 2441,
    nome: 'Letícia Vallejo Zaranski',
  },
  {
    rodada: 0,
    grupo: 17,
    matricula: 2433,
    nome: 'Ingrid Vitória Giese',
  },
  {
    rodada: 0,
    grupo: 17,
    matricula: 2500,
    nome: 'Lucas Pereira Luiz',
  },
  {
    rodada: 0,
    grupo: 17,
    matricula: 2400,
    nome: 'Murilo Henrique Ghignatti',
  },
  {
    rodada: 0,
    grupo: 18,
    matricula: 2428,
    nome: 'Iara Curcio Fadel',
  },
  {
    rodada: 0,
    grupo: 18,
    matricula: 2476,
    nome: 'Bruna Rodrigues Gazal Rocha',
  },
  {
    rodada: 0,
    grupo: 18,
    matricula: 2487,
    nome: 'Alisson Rizzi Kuzjman',
  },
  {
    rodada: 0,
    grupo: 18,
    matricula: 2523,
    nome: 'Aruni Serena Van Amstel',
  },
  {
    rodada: 0,
    grupo: 19,
    matricula: 2392,
    nome: 'Ana Carolina De Souza Costa',
  },
  {
    rodada: 0,
    grupo: 19,
    matricula: 2380,
    nome: 'Julia Zimmermann Cordeiro',
  },
  {
    rodada: 0,
    grupo: 19,
    matricula: 2499,
    nome: 'Neidivaldo Dias Da Silva Junior',
  },
  {
    rodada: 0,
    grupo: 19,
    matricula: 2519,
    nome: 'Murilo Vidal',
  },
  {
    rodada: 0,
    grupo: 20,
    matricula: 2364,
    nome: 'Isabela Makiolka Montingelli',
  },
  {
    rodada: 0,
    grupo: 20,
    matricula: 2416,
    nome: 'Giovana Garcia Ribeiro',
  },
  {
    rodada: 0,
    grupo: 20,
    matricula: 2375,
    nome: 'Jonathas Andrade Torquato',
  },
  {
    rodada: 0,
    grupo: 20,
    matricula: 2524,
    nome: 'Rodrigo Villas Boas Petroni',
  },
  {
    rodada: 0,
    grupo: 21,
    matricula: 2480,
    nome: 'Alexandra Dos Santos Gropp',
  },
  {
    rodada: 0,
    grupo: 21,
    matricula: 2429,
    nome: 'Bianca De Fatima Scharneski',
  },
  {
    rodada: 0,
    grupo: 21,
    matricula: 2411,
    nome: 'João Vitor Moreira',
  },
  {
    rodada: 0,
    grupo: 21,
    matricula: 2515,
    nome: 'Filipe Scorsin Cercal',
  },
  {
    rodada: 0,
    grupo: 22,
    matricula: 2378,
    nome: 'Sthefanny Ferreira Gonzaga',
  },
  {
    rodada: 0,
    grupo: 22,
    matricula: 2348,
    nome: 'Bernardo Augusto Monteiro De Oliveira Klingelfus',
  },
  {
    rodada: 0,
    grupo: 22,
    matricula: 2444,
    nome: 'Thiago Henrique Xavier Medeiros',
  },
  {
    rodada: 0,
    grupo: 22,
    matricula: 2373,
    nome: 'Ianca Polizelo',
  },
  {
    rodada: 0,
    grupo: 23,
    matricula: 2405,
    nome: 'Bruna Martins De Oliveira',
  },
  {
    rodada: 0,
    grupo: 23,
    matricula: 2506,
    nome: 'Vinícius Couto Tasso',
  },
  {
    rodada: 0,
    grupo: 23,
    matricula: 2357,
    nome: 'Mateus Maidel Alves Da Silva',
  },
  {
    rodada: 0,
    grupo: 23,
    matricula: 2356,
    nome: 'Ana Paula De Souza Marques',
  },
  {
    rodada: 0,
    grupo: 24,
    matricula: 2489,
    nome: 'Eduardo Batistel Zaniol',
  },
  {
    rodada: 0,
    grupo: 24,
    matricula: 2358,
    nome: 'Hamilton Wanderson Fortes De Menezes',
  },
  {
    rodada: 0,
    grupo: 24,
    matricula: 2455,
    nome: 'Fabiana Martins Budel',
  },
  {
    rodada: 0,
    grupo: 24,
    matricula: 2466,
    nome: 'Elliot Sabidussi',
  },
  {
    rodada: 0,
    grupo: 25,
    matricula: 2486,
    nome: 'Emerson Fabiano Marques Junior',
  },
  {
    rodada: 0,
    grupo: 25,
    matricula: 2351,
    nome: 'Rogério Bayer Ghizi',
  },
  {
    rodada: 0,
    grupo: 25,
    matricula: 2452,
    nome: 'Isabela Amanda Ciuneck',
  },
  {
    rodada: 0,
    grupo: 25,
    matricula: 2471,
    nome: 'Isabella Buzanello Martins',
  },
  {
    rodada: 0,
    grupo: 26,
    matricula: 2483,
    nome: 'Erick Martins Do Nascimento',
  },
  {
    rodada: 0,
    grupo: 26,
    matricula: 2521,
    nome: 'Bruno Padovan Soares De Souza',
  },
  {
    rodada: 0,
    grupo: 26,
    matricula: 2474,
    nome: 'Sali Goretti Stocco',
  },
  {
    rodada: 0,
    grupo: 26,
    matricula: 2460,
    nome: 'Tacila Fernanda Carneiro Evangelista',
  },
  {
    rodada: 0,
    grupo: 27,
    matricula: 2505,
    nome: 'André Schueda Menezes',
  },
  {
    rodada: 0,
    grupo: 27,
    matricula: 2425,
    nome: 'Guilherme Morais Lopes Dos Santos',
  },
  {
    rodada: 0,
    grupo: 27,
    matricula: 2472,
    nome: 'Amanda Lisboa',
  },
  {
    rodada: 0,
    grupo: 27,
    matricula: 2418,
    nome: 'Danielly J. P. Lazaro',
  },
  {
    rodada: 0,
    grupo: 28,
    matricula: 2502,
    nome: 'Carlos Augusto Toledo Martins',
  },
  {
    rodada: 0,
    grupo: 28,
    matricula: 2374,
    nome: 'Lucas Otavio Mariano Pinheiro Oro',
  },
  {
    rodada: 0,
    grupo: 28,
    matricula: 2385,
    nome: 'Erika Burei Alves',
  },
  {
    rodada: 0,
    grupo: 28,
    matricula: 2355,
    nome: 'Luana Mara Dalla Costa',
  },
  {
    rodada: 0,
    grupo: 29,
    matricula: 2468,
    nome: 'Márcio José Gurka Júnior',
  },
  {
    rodada: 0,
    grupo: 29,
    matricula: 2495,
    nome: 'Gustavo Dos Santos Polido',
  },
  {
    rodada: 0,
    grupo: 29,
    matricula: 2410,
    nome: 'Milena Almeida De Menezes Caldas',
  },
  {
    rodada: 0,
    grupo: 29,
    matricula: 2363,
    nome: 'Natália Schueda Menezes',
  },
  {
    rodada: 0,
    grupo: 30,
    matricula: 2514,
    nome: 'Pedro Henrique Schisler Squisati',
  },
  {
    rodada: 0,
    grupo: 30,
    matricula: 2498,
    nome: 'Levy Gomes Dos Santos Neto',
  },
  {
    rodada: 0,
    grupo: 30,
    matricula: 2391,
    nome: 'Lígia Naomi Nakase',
  },
  {
    rodada: 0,
    grupo: 30,
    matricula: 2388,
    nome: 'Katherine Finn Zander',
  },
  {
    rodada: 0,
    grupo: 31,
    matricula: 2415,
    nome: 'Lucas Augusto De Castro Coelho',
  },
  {
    rodada: 0,
    grupo: 31,
    matricula: 2492,
    nome: 'Luiz Siqueira',
  },
  {
    rodada: 0,
    grupo: 31,
    matricula: 2417,
    nome: 'Luísa Bacichett Trabulci',
  },
  {
    rodada: 0,
    grupo: 31,
    matricula: 2435,
    nome: 'Suzy Shiori Sakano',
  },
  {
    rodada: 0,
    grupo: 32,
    matricula: 2508,
    nome: 'Victor Henrique De Moura Netto',
  },
  {
    rodada: 0,
    grupo: 32,
    matricula: 2389,
    nome: 'Eduardo Vinicius Schroeder',
  },
  {
    rodada: 0,
    grupo: 32,
    matricula: 2427,
    nome: 'Naomi Nakanishi Frigotto',
  },
  {
    rodada: 0,
    grupo: 32,
    matricula: 2449,
    nome: 'Isabela Luiza Molin De Siqueira',
  },
  {
    rodada: 0,
    grupo: 33,
    matricula: 2354,
    nome: 'Leandro Allysson Joo',
  },
  {
    rodada: 0,
    grupo: 33,
    matricula: 2399,
    nome: 'Raul Gomes Pimentel De Almeida',
  },
  {
    rodada: 0,
    grupo: 33,
    matricula: 2432,
    nome: 'Rafaela Angelon',
  },
  {
    rodada: 0,
    grupo: 33,
    matricula: 2453,
    nome: 'Ana Paula Vieira Roviero',
  },
  {
    rodada: 0,
    grupo: 34,
    matricula: 2527,
    nome: 'Pedro Fernando Martins',
  },
  {
    rodada: 0,
    grupo: 34,
    matricula: 2488,
    nome: 'Paulo Tadashi Tokikawa',
  },
  {
    rodada: 0,
    grupo: 34,
    matricula: 2394,
    nome: 'Mariana Florencio De Oliveira',
  },
  {
    rodada: 0,
    grupo: 34,
    matricula: 2477,
    nome: 'Fernanda Alves Martinhaki',
  },
  {
    rodada: 0,
    grupo: 35,
    matricula: 2522,
    nome: 'Diogo Andreatta Bergamo',
  },
  {
    rodada: 0,
    grupo: 35,
    matricula: 2493,
    nome: 'Guilherme Pinho Gomig',
  },
  {
    rodada: 0,
    grupo: 35,
    matricula: 2467,
    nome: 'Flavia Lombardi Maceira',
  },
  {
    rodada: 0,
    grupo: 35,
    matricula: 2379,
    nome: 'Cássia Megumi Fuku Oban',
  },
  {
    rodada: 0,
    grupo: 36,
    matricula: 2372,
    nome: 'Gabriel Torres Andreassa',
  },
  {
    rodada: 0,
    grupo: 36,
    matricula: 2491,
    nome: 'Alison Hudson De Souza',
  },
  {
    rodada: 0,
    grupo: 36,
    matricula: 2461,
    nome: 'Kimberlly Hapuque Da Silva Brito',
  },
  {
    rodada: 0,
    grupo: 36,
    matricula: 2458,
    nome: 'Stefany Jardim Rodrigues',
  },
  {
    rodada: 0,
    grupo: 37,
    matricula: 2482,
    nome: 'Guilherme Barbosa Candido',
  },
  {
    rodada: 0,
    grupo: 37,
    matricula: 2459,
    nome: 'Felipe Seolin Bento',
  },
  {
    rodada: 0,
    grupo: 37,
    matricula: 2420,
    nome: 'Mônica Falat Reva Dell Agnolo',
  },
  {
    rodada: 0,
    grupo: 37,
    matricula: 2479,
    nome: 'Alis Eugenio Frentzel',
  },
  {
    rodada: 0,
    grupo: 38,
    matricula: 2424,
    nome: 'João Carlos Delay Junior',
  },
  {
    rodada: 0,
    grupo: 38,
    matricula: 2446,
    nome: 'Felipe Alves Barboza',
  },
  {
    rodada: 0,
    grupo: 38,
    matricula: 2454,
    nome: 'Maria Luiza Santos Do Amaral',
  },
  {
    rodada: 0,
    grupo: 38,
    matricula: 2386,
    nome: 'Eloísa De Oliveira Almeida',
  },
  {
    rodada: 0,
    grupo: 39,
    matricula: 2393,
    nome: 'João Pedro Picolo',
  },
  {
    rodada: 0,
    grupo: 39,
    matricula: 2470,
    nome: 'Weslley Felipe De Siqueira Dos Santos',
  },
  {
    rodada: 0,
    grupo: 39,
    matricula: 2401,
    nome: 'Barbara Cristina Xavier',
  },
  {
    rodada: 0,
    grupo: 39,
    matricula: 2431,
    nome: 'Barbra Eliza Domingues Da Silva',
  },
  {
    rodada: 0,
    grupo: 40,
    matricula: 2414,
    nome: 'Marco Antônio Barbosa Zulian',
  },
  {
    rodada: 0,
    grupo: 40,
    matricula: 2349,
    nome: 'Rafael Matheus Chaves Silveira',
  },
  {
    rodada: 0,
    grupo: 40,
    matricula: 2366,
    nome: 'Maria Teresa Kravetz Andrioli',
  },
  {
    rodada: 0,
    grupo: 40,
    matricula: 2359,
    nome: 'Alessandra Fernandes Lacerda',
  },
  {
    rodada: 0,
    grupo: 41,
    matricula: 2494,
    nome: 'Arthur Giacobbe Kusma De Pauli',
  },
  {
    rodada: 0,
    grupo: 41,
    matricula: 2353,
    nome: 'Alex Freitas Soares',
  },
  {
    rodada: 0,
    grupo: 41,
    matricula: 2456,
    nome: 'Carolina Martins Gonçalves',
  },
  {
    rodada: 0,
    grupo: 41,
    matricula: 2367,
    nome: 'Hanna Paterno Coutinho Ferreira',
  },
  {
    rodada: 0,
    grupo: 42,
    matricula: 2484,
    nome: 'Filipe Xavier Melnik',
  },
  {
    rodada: 0,
    grupo: 42,
    matricula: 2462,
    nome: 'Renato Ferreira Godinho',
  },
  {
    rodada: 0,
    grupo: 42,
    matricula: 2382,
    nome: 'Fernanda Mayumi Obayashi',
  },
  {
    rodada: 0,
    grupo: 42,
    matricula: 2365,
    nome: 'Caroline Revay Franciosi',
  },
  {
    rodada: 0,
    grupo: 43,
    matricula: 2504,
    nome: 'André Luís Arns Guimarães',
  },
  {
    rodada: 0,
    grupo: 43,
    matricula: 2362,
    nome: 'Gustavo Monkolski Tatarem',
  },
  {
    rodada: 0,
    grupo: 43,
    matricula: 2404,
    nome: 'Eduardo Cristiano Franco',
  },
  {
    rodada: 0,
    grupo: 43,
    matricula: 2513,
    nome: 'Pedro Henrique Cordeiro Soares',
  },
  {
    rodada: 0,
    grupo: 44,
    matricula: 2398,
    nome: 'Marlon Griebeler Da Hora',
  },
  {
    rodada: 0,
    grupo: 44,
    matricula: 2516,
    nome: 'William Schineider Rabelo',
  },
  {
    rodada: 0,
    grupo: 44,
    matricula: 2403,
    nome: 'João Gustavo Król',
  },
  {
    rodada: 0,
    grupo: 44,
    matricula: 2490,
    nome: 'Gustavo Esteves Fernandes',
  },
  {
    rodada: 0,
    grupo: 45,
    matricula: 2451,
    nome: 'Enzo Trevisan Topanotti',
  },
  {
    rodada: 0,
    grupo: 45,
    matricula: 2525,
    nome: 'André Shizuo Hachiguti De Quadros',
  },
  {
    rodada: 0,
    grupo: 45,
    matricula: 2501,
    nome: 'Eros Maurilio De Oliveira Silvio Doro Pereira',
  },
  {
    rodada: 0,
    grupo: 45,
    matricula: 2352,
    nome: 'Saulo Alberto Cintra Roseiro Junior',
  },
  {
    rodada: 1,
    grupo: 1,
    matricula: 2370,
    nome: 'Djenifer Renata Pereira',
  },
  {
    rodada: 1,
    grupo: 1,
    matricula: 2408,
    nome: 'Gabriele Batista Do Nascimento',
  },
  {
    rodada: 1,
    grupo: 1,
    matricula: 2394,
    nome: 'Mariana Florencio De Oliveira',
  },
  {
    rodada: 1,
    grupo: 2,
    matricula: 2469,
    nome: 'Lucas Yoshio Nakano',
  },
  {
    rodada: 1,
    grupo: 2,
    matricula: 2369,
    nome: 'Kauane Santana Da Rosa',
  },
  {
    rodada: 1,
    grupo: 2,
    matricula: 2436,
    nome: 'Maria Teresa Ferreira Lima De Almeida',
  },
  {
    rodada: 1,
    grupo: 2,
    matricula: 2400,
    nome: 'Murilo Henrique Ghignatti',
  },
  {
    rodada: 1,
    grupo: 3,
    matricula: 2520,
    nome: 'Leonardo Barbosa Burgomeister',
  },
  {
    rodada: 1,
    grupo: 3,
    matricula: 2434,
    nome: 'Ana Bittencourt Vidigal',
  },
  {
    rodada: 1,
    grupo: 3,
    matricula: 2457,
    nome: 'Alessandra Boscardin Aver',
  },
  {
    rodada: 1,
    grupo: 3,
    matricula: 2496,
    nome: 'Vitor Aguiar Treglia',
  },
  {
    rodada: 1,
    grupo: 4,
    matricula: 2445,
    nome: 'Matheus Dos Santos Pedrozo De Lima',
  },
  {
    rodada: 1,
    grupo: 4,
    matricula: 2509,
    nome: 'Cesar André Costa Vaz',
  },
  {
    rodada: 1,
    grupo: 4,
    matricula: 2443,
    nome: 'Natalia Seixas Dias',
  },
  {
    rodada: 1,
    grupo: 4,
    matricula: 2417,
    nome: 'Luísa Bacichett Trabulci',
  },
  {
    rodada: 1,
    grupo: 5,
    matricula: 2503,
    nome: 'Bernardo Dos Reis De Melo',
  },
  {
    rodada: 1,
    grupo: 5,
    matricula: 2368,
    nome: 'Bruna Naomi Yamanaka Silva',
  },
  {
    rodada: 1,
    grupo: 5,
    matricula: 2396,
    nome: 'Ana Paula Kessler Gonçalves',
  },
  {
    rodada: 1,
    grupo: 5,
    matricula: 2498,
    nome: 'Levy Gomes Dos Santos Neto',
  },
  {
    rodada: 1,
    grupo: 6,
    matricula: 2377,
    nome: 'Oswaldo Da Silva Schermach',
  },
  {
    rodada: 1,
    grupo: 6,
    matricula: 2510,
    nome: 'Julio Teixeira Bojan',
  },
  {
    rodada: 1,
    grupo: 6,
    matricula: 2371,
    nome: 'Andrea Alexandra Sánez Oquendo',
  },
  {
    rodada: 1,
    grupo: 6,
    matricula: 2449,
    nome: 'Isabela Luiza Molin De Siqueira',
  },
  {
    rodada: 1,
    grupo: 7,
    matricula: 2430,
    nome: 'Larissa Paschoalin',
  },
  {
    rodada: 1,
    grupo: 7,
    matricula: 2384,
    nome: 'Gabriela Bogomolof Taquegami',
  },
  {
    rodada: 1,
    grupo: 7,
    matricula: 2511,
    nome: 'Herivelton José Gomes Da Trindade Júnior',
  },
  {
    rodada: 1,
    grupo: 7,
    matricula: 2465,
    nome: 'Matheus Henrique Tambosi',
  },
  {
    rodada: 1,
    grupo: 8,
    matricula: 2422,
    nome: 'Raquel Daleffi Zocoler',
  },
  {
    rodada: 1,
    grupo: 8,
    matricula: 2473,
    nome: 'Laís Affornali Fernandes',
  },
  {
    rodada: 1,
    grupo: 8,
    matricula: 2426,
    nome: 'Matheus Teixeira Souza',
  },
  {
    rodada: 1,
    grupo: 8,
    matricula: 2462,
    nome: 'Renato Ferreira Godinho',
  },
  {
    rodada: 1,
    grupo: 9,
    matricula: 2464,
    nome: 'Isabela Martin Silva',
  },
  {
    rodada: 1,
    grupo: 9,
    matricula: 2383,
    nome: 'Alessandra Souza Da Silva',
  },
  {
    rodada: 1,
    grupo: 9,
    matricula: 2448,
    nome: 'Gabriel Vieira Rodrigues',
  },
  {
    rodada: 1,
    grupo: 9,
    matricula: 2518,
    nome: 'Frederico Westphalen Mendes Machado',
  },
  {
    rodada: 1,
    grupo: 10,
    matricula: 2413,
    nome: 'Letícia Camargo De Sá Silva',
  },
  {
    rodada: 1,
    grupo: 10,
    matricula: 2390,
    nome: 'Marcus Augusto Ferreira Dudeque',
  },
  {
    rodada: 1,
    grupo: 10,
    matricula: 2526,
    nome: 'Guilerme Moreira Ribeiro Barciki',
  },
  {
    rodada: 1,
    grupo: 10,
    matricula: 2406,
    nome: 'Helen Skorupski Sloboda',
  },
  {
    rodada: 1,
    grupo: 11,
    matricula: 2440,
    nome: 'Natália Grein Silva',
  },
  {
    rodada: 1,
    grupo: 11,
    matricula: 2409,
    nome: 'Alan Renato Bunese',
  },
  {
    rodada: 1,
    grupo: 11,
    matricula: 2463,
    nome: 'Francisco Lucas Rezende',
  },
  {
    rodada: 1,
    grupo: 11,
    matricula: 2447,
    nome: 'Ana Luisa Duda Stege',
  },
  {
    rodada: 1,
    grupo: 12,
    matricula: 2442,
    nome: 'Isadora Rossetto Nogueira Drummond',
  },
  {
    rodada: 1,
    grupo: 12,
    matricula: 2485,
    nome: 'Gabriel Puppi Gozzo',
  },
  {
    rodada: 1,
    grupo: 12,
    matricula: 2397,
    nome: 'Eduardo Rosso Barbosa',
  },
  {
    rodada: 1,
    grupo: 12,
    matricula: 2416,
    nome: 'Giovana Garcia Ribeiro',
  },
  {
    rodada: 1,
    grupo: 13,
    matricula: 2412,
    nome: 'Jéssica Akemi Meguro',
  },
  {
    rodada: 1,
    grupo: 13,
    matricula: 2360,
    nome: 'Mario Morais Neto',
  },
  {
    rodada: 1,
    grupo: 13,
    matricula: 2350,
    nome: 'Alessandro Maciel Schmidt',
  },
  {
    rodada: 1,
    grupo: 13,
    matricula: 2478,
    nome: 'Bianca De Oliveira Brecailo',
  },
  {
    rodada: 1,
    grupo: 14,
    matricula: 2421,
    nome: 'Ianara De Souza Maldaner',
  },
  {
    rodada: 1,
    grupo: 14,
    matricula: 2481,
    nome: 'Bruno Yuiti Leão Imai',
  },
  {
    rodada: 1,
    grupo: 14,
    matricula: 2517,
    nome: 'Jean Ricardo Grein',
  },
  {
    rodada: 1,
    grupo: 14,
    matricula: 2431,
    nome: 'Barbra Eliza Domingues Da Silva',
  },
  {
    rodada: 1,
    grupo: 15,
    matricula: 2439,
    nome: 'Jady Torralvo Alves',
  },
  {
    rodada: 1,
    grupo: 15,
    matricula: 2475,
    nome: 'Geovanna Kasemirinski Da Silva',
  },
  {
    rodada: 1,
    grupo: 15,
    matricula: 2407,
    nome: 'Bruno Siedekum Thuma',
  },
  {
    rodada: 1,
    grupo: 15,
    matricula: 2522,
    nome: 'Diogo Andreatta Bergamo',
  },
  {
    rodada: 1,
    grupo: 16,
    matricula: 2395,
    nome: 'Giulia Andreazza Amaral',
  },
  {
    rodada: 1,
    grupo: 16,
    matricula: 2419,
    nome: 'Marina De Domenico Salioni Dubuc',
  },
  {
    rodada: 1,
    grupo: 16,
    matricula: 2361,
    nome: 'Leonardo José Zanotti',
  },
  {
    rodada: 1,
    grupo: 16,
    matricula: 2459,
    nome: 'Felipe Seolin Bento',
  },
  {
    rodada: 1,
    grupo: 17,
    matricula: 2441,
    nome: 'Letícia Vallejo Zaranski',
  },
  {
    rodada: 1,
    grupo: 17,
    matricula: 2433,
    nome: 'Ingrid Vitória Giese',
  },
  {
    rodada: 1,
    grupo: 17,
    matricula: 2500,
    nome: 'Lucas Pereira Luiz',
  },
  {
    rodada: 1,
    grupo: 17,
    matricula: 2502,
    nome: 'Carlos Augusto Toledo Martins',
  },
  {
    rodada: 1,
    grupo: 18,
    matricula: 2476,
    nome: 'Bruna Rodrigues Gazal Rocha',
  },
  {
    rodada: 1,
    grupo: 18,
    matricula: 2487,
    nome: 'Alisson Rizzi Kuzjman',
  },
  {
    rodada: 1,
    grupo: 18,
    matricula: 2523,
    nome: 'Aruni Serena Van Amstel',
  },
  {
    rodada: 1,
    grupo: 18,
    matricula: 2402,
    nome: 'Deborah Eberle Dos Santos',
  },
  {
    rodada: 1,
    grupo: 19,
    matricula: 2392,
    nome: 'Ana Carolina De Souza Costa',
  },
  {
    rodada: 1,
    grupo: 19,
    matricula: 2380,
    nome: 'Julia Zimmermann Cordeiro',
  },
  {
    rodada: 1,
    grupo: 19,
    matricula: 2499,
    nome: 'Neidivaldo Dias Da Silva Junior',
  },
  {
    rodada: 1,
    grupo: 19,
    matricula: 2525,
    nome: 'André Shizuo Hachiguti De Quadros',
  },
  {
    rodada: 1,
    grupo: 20,
    matricula: 2364,
    nome: 'Isabela Makiolka Montingelli',
  },
  {
    rodada: 1,
    grupo: 20,
    matricula: 2375,
    nome: 'Jonathas Andrade Torquato',
  },
  {
    rodada: 1,
    grupo: 20,
    matricula: 2524,
    nome: 'Rodrigo Villas Boas Petroni',
  },
  {
    rodada: 1,
    grupo: 20,
    matricula: 2437,
    nome: 'Natalia Da Rosa',
  },
  {
    rodada: 1,
    grupo: 21,
    matricula: 2429,
    nome: 'Bianca De Fatima Scharneski',
  },
  {
    rodada: 1,
    grupo: 21,
    matricula: 2411,
    nome: 'João Vitor Moreira',
  },
  {
    rodada: 1,
    grupo: 21,
    matricula: 2515,
    nome: 'Filipe Scorsin Cercal',
  },
  {
    rodada: 1,
    grupo: 21,
    matricula: 2386,
    nome: 'Eloísa De Oliveira Almeida',
  },
  {
    rodada: 1,
    grupo: 22,
    matricula: 2348,
    nome: 'Bernardo Augusto Monteiro De Oliveira Klingelfus',
  },
  {
    rodada: 1,
    grupo: 22,
    matricula: 2444,
    nome: 'Thiago Henrique Xavier Medeiros',
  },
  {
    rodada: 1,
    grupo: 22,
    matricula: 2373,
    nome: 'Ianca Polizelo',
  },
  {
    rodada: 1,
    grupo: 22,
    matricula: 2423,
    nome: 'Daniella Onishi',
  },
  {
    rodada: 1,
    grupo: 23,
    matricula: 2405,
    nome: 'Bruna Martins De Oliveira',
  },
  {
    rodada: 1,
    grupo: 23,
    matricula: 2506,
    nome: 'Vinícius Couto Tasso',
  },
  {
    rodada: 1,
    grupo: 23,
    matricula: 2357,
    nome: 'Mateus Maidel Alves Da Silva',
  },
  {
    rodada: 1,
    grupo: 23,
    matricula: 2471,
    nome: 'Isabella Buzanello Martins',
  },
  {
    rodada: 1,
    grupo: 24,
    matricula: 2489,
    nome: 'Eduardo Batistel Zaniol',
  },
  {
    rodada: 1,
    grupo: 24,
    matricula: 2455,
    nome: 'Fabiana Martins Budel',
  },
  {
    rodada: 1,
    grupo: 24,
    matricula: 2466,
    nome: 'Elliot Sabidussi',
  },
  {
    rodada: 1,
    grupo: 24,
    matricula: 2507,
    nome: 'Gustavo Kumasawa',
  },
  {
    rodada: 1,
    grupo: 25,
    matricula: 2486,
    nome: 'Emerson Fabiano Marques Junior',
  },
  {
    rodada: 1,
    grupo: 25,
    matricula: 2351,
    nome: 'Rogério Bayer Ghizi',
  },
  {
    rodada: 1,
    grupo: 25,
    matricula: 2452,
    nome: 'Isabela Amanda Ciuneck',
  },
  {
    rodada: 1,
    grupo: 25,
    matricula: 2418,
    nome: 'Danielly J. P. Lazaro',
  },
  {
    rodada: 1,
    grupo: 26,
    matricula: 2483,
    nome: 'Erick Martins Do Nascimento',
  },
  {
    rodada: 1,
    grupo: 26,
    matricula: 2474,
    nome: 'Sali Goretti Stocco',
  },
  {
    rodada: 1,
    grupo: 26,
    matricula: 2460,
    nome: 'Tacila Fernanda Carneiro Evangelista',
  },
  {
    rodada: 1,
    grupo: 26,
    matricula: 2519,
    nome: 'Murilo Vidal',
  },
  {
    rodada: 1,
    grupo: 27,
    matricula: 2505,
    nome: 'André Schueda Menezes',
  },
  {
    rodada: 1,
    grupo: 27,
    matricula: 2425,
    nome: 'Guilherme Morais Lopes Dos Santos',
  },
  {
    rodada: 1,
    grupo: 27,
    matricula: 2472,
    nome: 'Amanda Lisboa',
  },
  {
    rodada: 1,
    grupo: 27,
    matricula: 2356,
    nome: 'Ana Paula De Souza Marques',
  },
  {
    rodada: 1,
    grupo: 28,
    matricula: 2374,
    nome: 'Lucas Otavio Mariano Pinheiro Oro',
  },
  {
    rodada: 1,
    grupo: 28,
    matricula: 2385,
    nome: 'Erika Burei Alves',
  },
  {
    rodada: 1,
    grupo: 28,
    matricula: 2355,
    nome: 'Luana Mara Dalla Costa',
  },
  {
    rodada: 1,
    grupo: 28,
    matricula: 2491,
    nome: 'Alison Hudson De Souza',
  },
  {
    rodada: 1,
    grupo: 29,
    matricula: 2495,
    nome: 'Gustavo Dos Santos Polido',
  },
  {
    rodada: 1,
    grupo: 29,
    matricula: 2410,
    nome: 'Milena Almeida De Menezes Caldas',
  },
  {
    rodada: 1,
    grupo: 29,
    matricula: 2363,
    nome: 'Natália Schueda Menezes',
  },
  {
    rodada: 1,
    grupo: 29,
    matricula: 2349,
    nome: 'Rafael Matheus Chaves Silveira',
  },
  {
    rodada: 1,
    grupo: 30,
    matricula: 2514,
    nome: 'Pedro Henrique Schisler Squisati',
  },
  {
    rodada: 1,
    grupo: 30,
    matricula: 2391,
    nome: 'Lígia Naomi Nakase',
  },
  {
    rodada: 1,
    grupo: 30,
    matricula: 2388,
    nome: 'Katherine Finn Zander',
  },
  {
    rodada: 1,
    grupo: 30,
    matricula: 2468,
    nome: 'Márcio José Gurka Júnior',
  },
  {
    rodada: 1,
    grupo: 31,
    matricula: 2415,
    nome: 'Lucas Augusto De Castro Coelho',
  },
  {
    rodada: 1,
    grupo: 31,
    matricula: 2492,
    nome: 'Luiz Siqueira',
  },
  {
    rodada: 1,
    grupo: 31,
    matricula: 2435,
    nome: 'Suzy Shiori Sakano',
  },
  {
    rodada: 1,
    grupo: 31,
    matricula: 2438,
    nome: 'Yasmin Mayer',
  },
  {
    rodada: 1,
    grupo: 32,
    matricula: 2508,
    nome: 'Victor Henrique De Moura Netto',
  },
  {
    rodada: 1,
    grupo: 32,
    matricula: 2389,
    nome: 'Eduardo Vinicius Schroeder',
  },
  {
    rodada: 1,
    grupo: 32,
    matricula: 2427,
    nome: 'Naomi Nakanishi Frigotto',
  },
  {
    rodada: 1,
    grupo: 32,
    matricula: 2381,
    nome: 'Melissa Fernanda Rodrigues Siqueira',
  },
  {
    rodada: 1,
    grupo: 33,
    matricula: 2354,
    nome: 'Leandro Allysson Joo',
  },
  {
    rodada: 1,
    grupo: 33,
    matricula: 2432,
    nome: 'Rafaela Angelon',
  },
  {
    rodada: 1,
    grupo: 33,
    matricula: 2453,
    nome: 'Ana Paula Vieira Roviero',
  },
  {
    rodada: 1,
    grupo: 33,
    matricula: 2513,
    nome: 'Pedro Henrique Cordeiro Soares',
  },
  {
    rodada: 1,
    grupo: 34,
    matricula: 2527,
    nome: 'Pedro Fernando Martins',
  },
  {
    rodada: 1,
    grupo: 34,
    matricula: 2488,
    nome: 'Paulo Tadashi Tokikawa',
  },
  {
    rodada: 1,
    grupo: 34,
    matricula: 2477,
    nome: 'Fernanda Alves Martinhaki',
  },
  {
    rodada: 1,
    grupo: 34,
    matricula: 2428,
    nome: 'Iara Curcio Fadel',
  },
  {
    rodada: 1,
    grupo: 35,
    matricula: 2493,
    nome: 'Guilherme Pinho Gomig',
  },
  {
    rodada: 1,
    grupo: 35,
    matricula: 2467,
    nome: 'Flavia Lombardi Maceira',
  },
  {
    rodada: 1,
    grupo: 35,
    matricula: 2379,
    nome: 'Cássia Megumi Fuku Oban',
  },
  {
    rodada: 1,
    grupo: 35,
    matricula: 2399,
    nome: 'Raul Gomes Pimentel De Almeida',
  },
  {
    rodada: 1,
    grupo: 36,
    matricula: 2372,
    nome: 'Gabriel Torres Andreassa',
  },
  {
    rodada: 1,
    grupo: 36,
    matricula: 2461,
    nome: 'Kimberlly Hapuque Da Silva Brito',
  },
  {
    rodada: 1,
    grupo: 36,
    matricula: 2458,
    nome: 'Stefany Jardim Rodrigues',
  },
  {
    rodada: 1,
    grupo: 36,
    matricula: 2398,
    nome: 'Marlon Griebeler Da Hora',
  },
  {
    rodada: 1,
    grupo: 37,
    matricula: 2482,
    nome: 'Guilherme Barbosa Candido',
  },
  {
    rodada: 1,
    grupo: 37,
    matricula: 2420,
    nome: 'Mônica Falat Reva Dell Agnolo',
  },
  {
    rodada: 1,
    grupo: 37,
    matricula: 2479,
    nome: 'Alis Eugenio Frentzel',
  },
  {
    rodada: 1,
    grupo: 37,
    matricula: 2358,
    nome: 'Hamilton Wanderson Fortes De Menezes',
  },
  {
    rodada: 1,
    grupo: 38,
    matricula: 2424,
    nome: 'João Carlos Delay Junior',
  },
  {
    rodada: 1,
    grupo: 38,
    matricula: 2446,
    nome: 'Felipe Alves Barboza',
  },
  {
    rodada: 1,
    grupo: 38,
    matricula: 2454,
    nome: 'Maria Luiza Santos Do Amaral',
  },
  {
    rodada: 1,
    grupo: 38,
    matricula: 2480,
    nome: 'Alexandra Dos Santos Gropp',
  },
  {
    rodada: 1,
    grupo: 39,
    matricula: 2393,
    nome: 'João Pedro Picolo',
  },
  {
    rodada: 1,
    grupo: 39,
    matricula: 2470,
    nome: 'Weslley Felipe De Siqueira Dos Santos',
  },
  {
    rodada: 1,
    grupo: 39,
    matricula: 2401,
    nome: 'Barbara Cristina Xavier',
  },
  {
    rodada: 1,
    grupo: 39,
    matricula: 2378,
    nome: 'Sthefanny Ferreira Gonzaga',
  },
  {
    rodada: 1,
    grupo: 40,
    matricula: 2414,
    nome: 'Marco Antônio Barbosa Zulian',
  },
  {
    rodada: 1,
    grupo: 40,
    matricula: 2366,
    nome: 'Maria Teresa Kravetz Andrioli',
  },
  {
    rodada: 1,
    grupo: 40,
    matricula: 2359,
    nome: 'Alessandra Fernandes Lacerda',
  },
  {
    rodada: 1,
    grupo: 40,
    matricula: 2376,
    nome: 'Samuel Eberhardt',
  },
  {
    rodada: 1,
    grupo: 41,
    matricula: 2494,
    nome: 'Arthur Giacobbe Kusma De Pauli',
  },
  {
    rodada: 1,
    grupo: 41,
    matricula: 2456,
    nome: 'Carolina Martins Gonçalves',
  },
  {
    rodada: 1,
    grupo: 41,
    matricula: 2367,
    nome: 'Hanna Paterno Coutinho Ferreira',
  },
  {
    rodada: 1,
    grupo: 41,
    matricula: 2450,
    nome: 'Henrique Castro Santos',
  },
  {
    rodada: 1,
    grupo: 42,
    matricula: 2484,
    nome: 'Filipe Xavier Melnik',
  },
  {
    rodada: 1,
    grupo: 42,
    matricula: 2382,
    nome: 'Fernanda Mayumi Obayashi',
  },
  {
    rodada: 1,
    grupo: 42,
    matricula: 2365,
    nome: 'Caroline Revay Franciosi',
  },
  {
    rodada: 1,
    grupo: 42,
    matricula: 2353,
    nome: 'Alex Freitas Soares',
  },
  {
    rodada: 1,
    grupo: 43,
    matricula: 2504,
    nome: 'André Luís Arns Guimarães',
  },
  {
    rodada: 1,
    grupo: 43,
    matricula: 2362,
    nome: 'Gustavo Monkolski Tatarem',
  },
  {
    rodada: 1,
    grupo: 43,
    matricula: 2404,
    nome: 'Eduardo Cristiano Franco',
  },
  {
    rodada: 1,
    grupo: 43,
    matricula: 2521,
    nome: 'Bruno Padovan Soares De Souza',
  },
  {
    rodada: 1,
    grupo: 44,
    matricula: 2516,
    nome: 'William Schineider Rabelo',
  },
  {
    rodada: 1,
    grupo: 44,
    matricula: 2403,
    nome: 'João Gustavo Król',
  },
  {
    rodada: 1,
    grupo: 44,
    matricula: 2490,
    nome: 'Gustavo Esteves Fernandes',
  },
  {
    rodada: 1,
    grupo: 44,
    matricula: 2512,
    nome: 'Pablo Enrique Harbar Penas',
  },
  {
    rodada: 1,
    grupo: 45,
    matricula: 2451,
    nome: 'Enzo Trevisan Topanotti',
  },
  {
    rodada: 1,
    grupo: 45,
    matricula: 2501,
    nome: 'Eros Maurilio De Oliveira Silvio Doro Pereira',
  },
  {
    rodada: 1,
    grupo: 45,
    matricula: 2352,
    nome: 'Saulo Alberto Cintra Roseiro Junior',
  },
  {
    rodada: 1,
    grupo: 45,
    matricula: 2497,
    nome: 'Pietro Ricardo Schoch Alves',
  },
  {
    rodada: 2,
    grupo: 1,
    matricula: 2408,
    nome: 'Gabriele Batista Do Nascimento',
  },
  {
    rodada: 2,
    grupo: 1,
    matricula: 2394,
    nome: 'Mariana Florencio De Oliveira',
  },
  {
    rodada: 2,
    grupo: 1,
    matricula: 2476,
    nome: 'Bruna Rodrigues Gazal Rocha',
  },
  {
    rodada: 2,
    grupo: 2,
    matricula: 2369,
    nome: 'Kauane Santana Da Rosa',
  },
  {
    rodada: 2,
    grupo: 2,
    matricula: 2436,
    nome: 'Maria Teresa Ferreira Lima De Almeida',
  },
  {
    rodada: 2,
    grupo: 2,
    matricula: 2400,
    nome: 'Murilo Henrique Ghignatti',
  },
  {
    rodada: 2,
    grupo: 2,
    matricula: 2515,
    nome: 'Filipe Scorsin Cercal',
  },
  {
    rodada: 2,
    grupo: 3,
    matricula: 2434,
    nome: 'Ana Bittencourt Vidigal',
  },
  {
    rodada: 2,
    grupo: 3,
    matricula: 2457,
    nome: 'Alessandra Boscardin Aver',
  },
  {
    rodada: 2,
    grupo: 3,
    matricula: 2496,
    nome: 'Vitor Aguiar Treglia',
  },
  {
    rodada: 2,
    grupo: 3,
    matricula: 2372,
    nome: 'Gabriel Torres Andreassa',
  },
  {
    rodada: 2,
    grupo: 4,
    matricula: 2445,
    nome: 'Matheus Dos Santos Pedrozo De Lima',
  },
  {
    rodada: 2,
    grupo: 4,
    matricula: 2509,
    nome: 'Cesar André Costa Vaz',
  },
  {
    rodada: 2,
    grupo: 4,
    matricula: 2417,
    nome: 'Luísa Bacichett Trabulci',
  },
  {
    rodada: 2,
    grupo: 4,
    matricula: 2383,
    nome: 'Alessandra Souza Da Silva',
  },
  {
    rodada: 2,
    grupo: 5,
    matricula: 2503,
    nome: 'Bernardo Dos Reis De Melo',
  },
  {
    rodada: 2,
    grupo: 5,
    matricula: 2368,
    nome: 'Bruna Naomi Yamanaka Silva',
  },
  {
    rodada: 2,
    grupo: 5,
    matricula: 2498,
    nome: 'Levy Gomes Dos Santos Neto',
  },
  {
    rodada: 2,
    grupo: 5,
    matricula: 2421,
    nome: 'Ianara De Souza Maldaner',
  },
  {
    rodada: 2,
    grupo: 6,
    matricula: 2377,
    nome: 'Oswaldo Da Silva Schermach',
  },
  {
    rodada: 2,
    grupo: 6,
    matricula: 2510,
    nome: 'Julio Teixeira Bojan',
  },
  {
    rodada: 2,
    grupo: 6,
    matricula: 2449,
    nome: 'Isabela Luiza Molin De Siqueira',
  },
  {
    rodada: 2,
    grupo: 6,
    matricula: 2370,
    nome: 'Djenifer Renata Pereira',
  },
  {
    rodada: 2,
    grupo: 7,
    matricula: 2430,
    nome: 'Larissa Paschoalin',
  },
  {
    rodada: 2,
    grupo: 7,
    matricula: 2511,
    nome: 'Herivelton José Gomes Da Trindade Júnior',
  },
  {
    rodada: 2,
    grupo: 7,
    matricula: 2465,
    nome: 'Matheus Henrique Tambosi',
  },
  {
    rodada: 2,
    grupo: 7,
    matricula: 2371,
    nome: 'Andrea Alexandra Sánez Oquendo',
  },
  {
    rodada: 2,
    grupo: 8,
    matricula: 2422,
    nome: 'Raquel Daleffi Zocoler',
  },
  {
    rodada: 2,
    grupo: 8,
    matricula: 2473,
    nome: 'Laís Affornali Fernandes',
  },
  {
    rodada: 2,
    grupo: 8,
    matricula: 2462,
    nome: 'Renato Ferreira Godinho',
  },
  {
    rodada: 2,
    grupo: 8,
    matricula: 2403,
    nome: 'João Gustavo Król',
  },
  {
    rodada: 2,
    grupo: 9,
    matricula: 2464,
    nome: 'Isabela Martin Silva',
  },
  {
    rodada: 2,
    grupo: 9,
    matricula: 2448,
    nome: 'Gabriel Vieira Rodrigues',
  },
  {
    rodada: 2,
    grupo: 9,
    matricula: 2518,
    nome: 'Frederico Westphalen Mendes Machado',
  },
  {
    rodada: 2,
    grupo: 9,
    matricula: 2472,
    nome: 'Amanda Lisboa',
  },
  {
    rodada: 2,
    grupo: 10,
    matricula: 2413,
    nome: 'Letícia Camargo De Sá Silva',
  },
  {
    rodada: 2,
    grupo: 10,
    matricula: 2390,
    nome: 'Marcus Augusto Ferreira Dudeque',
  },
  {
    rodada: 2,
    grupo: 10,
    matricula: 2406,
    nome: 'Helen Skorupski Sloboda',
  },
  {
    rodada: 2,
    grupo: 10,
    matricula: 2520,
    nome: 'Leonardo Barbosa Burgomeister',
  },
  {
    rodada: 2,
    grupo: 11,
    matricula: 2409,
    nome: 'Alan Renato Bunese',
  },
  {
    rodada: 2,
    grupo: 11,
    matricula: 2463,
    nome: 'Francisco Lucas Rezende',
  },
  {
    rodada: 2,
    grupo: 11,
    matricula: 2447,
    nome: 'Ana Luisa Duda Stege',
  },
  {
    rodada: 2,
    grupo: 11,
    matricula: 2475,
    nome: 'Geovanna Kasemirinski Da Silva',
  },
  {
    rodada: 2,
    grupo: 12,
    matricula: 2442,
    nome: 'Isadora Rossetto Nogueira Drummond',
  },
  {
    rodada: 2,
    grupo: 12,
    matricula: 2485,
    nome: 'Gabriel Puppi Gozzo',
  },
  {
    rodada: 2,
    grupo: 12,
    matricula: 2416,
    nome: 'Giovana Garcia Ribeiro',
  },
  {
    rodada: 2,
    grupo: 12,
    matricula: 2526,
    nome: 'Guilerme Moreira Ribeiro Barciki',
  },
  {
    rodada: 2,
    grupo: 13,
    matricula: 2412,
    nome: 'Jéssica Akemi Meguro',
  },
  {
    rodada: 2,
    grupo: 13,
    matricula: 2360,
    nome: 'Mario Morais Neto',
  },
  {
    rodada: 2,
    grupo: 13,
    matricula: 2478,
    nome: 'Bianca De Oliveira Brecailo',
  },
  {
    rodada: 2,
    grupo: 13,
    matricula: 2500,
    nome: 'Lucas Pereira Luiz',
  },
  {
    rodada: 2,
    grupo: 14,
    matricula: 2481,
    nome: 'Bruno Yuiti Leão Imai',
  },
  {
    rodada: 2,
    grupo: 14,
    matricula: 2517,
    nome: 'Jean Ricardo Grein',
  },
  {
    rodada: 2,
    grupo: 14,
    matricula: 2431,
    nome: 'Barbra Eliza Domingues Da Silva',
  },
  {
    rodada: 2,
    grupo: 14,
    matricula: 2452,
    nome: 'Isabela Amanda Ciuneck',
  },
  {
    rodada: 2,
    grupo: 15,
    matricula: 2439,
    nome: 'Jady Torralvo Alves',
  },
  {
    rodada: 2,
    grupo: 15,
    matricula: 2407,
    nome: 'Bruno Siedekum Thuma',
  },
  {
    rodada: 2,
    grupo: 15,
    matricula: 2522,
    nome: 'Diogo Andreatta Bergamo',
  },
  {
    rodada: 2,
    grupo: 15,
    matricula: 2382,
    nome: 'Fernanda Mayumi Obayashi',
  },
  {
    rodada: 2,
    grupo: 16,
    matricula: 2395,
    nome: 'Giulia Andreazza Amaral',
  },
  {
    rodada: 2,
    grupo: 16,
    matricula: 2361,
    nome: 'Leonardo José Zanotti',
  },
  {
    rodada: 2,
    grupo: 16,
    matricula: 2459,
    nome: 'Felipe Seolin Bento',
  },
  {
    rodada: 2,
    grupo: 16,
    matricula: 2384,
    nome: 'Gabriela Bogomolof Taquegami',
  },
  {
    rodada: 2,
    grupo: 17,
    matricula: 2441,
    nome: 'Letícia Vallejo Zaranski',
  },
  {
    rodada: 2,
    grupo: 17,
    matricula: 2433,
    nome: 'Ingrid Vitória Giese',
  },
  {
    rodada: 2,
    grupo: 17,
    matricula: 2502,
    nome: 'Carlos Augusto Toledo Martins',
  },
  {
    rodada: 2,
    grupo: 17,
    matricula: 2397,
    nome: 'Eduardo Rosso Barbosa',
  },
  {
    rodada: 2,
    grupo: 18,
    matricula: 2487,
    nome: 'Alisson Rizzi Kuzjman',
  },
  {
    rodada: 2,
    grupo: 18,
    matricula: 2523,
    nome: 'Aruni Serena Van Amstel',
  },
  {
    rodada: 2,
    grupo: 18,
    matricula: 2402,
    nome: 'Deborah Eberle Dos Santos',
  },
  {
    rodada: 2,
    grupo: 18,
    matricula: 2392,
    nome: 'Ana Carolina De Souza Costa',
  },
  {
    rodada: 2,
    grupo: 19,
    matricula: 2380,
    nome: 'Julia Zimmermann Cordeiro',
  },
  {
    rodada: 2,
    grupo: 19,
    matricula: 2499,
    nome: 'Neidivaldo Dias Da Silva Junior',
  },
  {
    rodada: 2,
    grupo: 19,
    matricula: 2525,
    nome: 'André Shizuo Hachiguti De Quadros',
  },
  {
    rodada: 2,
    grupo: 19,
    matricula: 2427,
    nome: 'Naomi Nakanishi Frigotto',
  },
  {
    rodada: 2,
    grupo: 20,
    matricula: 2364,
    nome: 'Isabela Makiolka Montingelli',
  },
  {
    rodada: 2,
    grupo: 20,
    matricula: 2524,
    nome: 'Rodrigo Villas Boas Petroni',
  },
  {
    rodada: 2,
    grupo: 20,
    matricula: 2437,
    nome: 'Natalia Da Rosa',
  },
  {
    rodada: 2,
    grupo: 20,
    matricula: 2501,
    nome: 'Eros Maurilio De Oliveira Silvio Doro Pereira',
  },
  {
    rodada: 2,
    grupo: 21,
    matricula: 2429,
    nome: 'Bianca De Fatima Scharneski',
  },
  {
    rodada: 2,
    grupo: 21,
    matricula: 2411,
    nome: 'João Vitor Moreira',
  },
  {
    rodada: 2,
    grupo: 21,
    matricula: 2386,
    nome: 'Eloísa De Oliveira Almeida',
  },
  {
    rodada: 2,
    grupo: 21,
    matricula: 2415,
    nome: 'Lucas Augusto De Castro Coelho',
  },
  {
    rodada: 2,
    grupo: 22,
    matricula: 2348,
    nome: 'Bernardo Augusto Monteiro De Oliveira Klingelfus',
  },
  {
    rodada: 2,
    grupo: 22,
    matricula: 2444,
    nome: 'Thiago Henrique Xavier Medeiros',
  },
  {
    rodada: 2,
    grupo: 22,
    matricula: 2423,
    nome: 'Daniella Onishi',
  },
  {
    rodada: 2,
    grupo: 22,
    matricula: 2456,
    nome: 'Carolina Martins Gonçalves',
  },
  {
    rodada: 2,
    grupo: 23,
    matricula: 2506,
    nome: 'Vinícius Couto Tasso',
  },
  {
    rodada: 2,
    grupo: 23,
    matricula: 2357,
    nome: 'Mateus Maidel Alves Da Silva',
  },
  {
    rodada: 2,
    grupo: 23,
    matricula: 2471,
    nome: 'Isabella Buzanello Martins',
  },
  {
    rodada: 2,
    grupo: 23,
    matricula: 2396,
    nome: 'Ana Paula Kessler Gonçalves',
  },
  {
    rodada: 2,
    grupo: 24,
    matricula: 2455,
    nome: 'Fabiana Martins Budel',
  },
  {
    rodada: 2,
    grupo: 24,
    matricula: 2466,
    nome: 'Elliot Sabidussi',
  },
  {
    rodada: 2,
    grupo: 24,
    matricula: 2507,
    nome: 'Gustavo Kumasawa',
  },
  {
    rodada: 2,
    grupo: 24,
    matricula: 2424,
    nome: 'João Carlos Delay Junior',
  },
  {
    rodada: 2,
    grupo: 25,
    matricula: 2486,
    nome: 'Emerson Fabiano Marques Junior',
  },
  {
    rodada: 2,
    grupo: 25,
    matricula: 2351,
    nome: 'Rogério Bayer Ghizi',
  },
  {
    rodada: 2,
    grupo: 25,
    matricula: 2418,
    nome: 'Danielly J. P. Lazaro',
  },
  {
    rodada: 2,
    grupo: 25,
    matricula: 2477,
    nome: 'Fernanda Alves Martinhaki',
  },
  {
    rodada: 2,
    grupo: 26,
    matricula: 2483,
    nome: 'Erick Martins Do Nascimento',
  },
  {
    rodada: 2,
    grupo: 26,
    matricula: 2460,
    nome: 'Tacila Fernanda Carneiro Evangelista',
  },
  {
    rodada: 2,
    grupo: 26,
    matricula: 2519,
    nome: 'Murilo Vidal',
  },
  {
    rodada: 2,
    grupo: 26,
    matricula: 2440,
    nome: 'Natália Grein Silva',
  },
  {
    rodada: 2,
    grupo: 27,
    matricula: 2505,
    nome: 'André Schueda Menezes',
  },
  {
    rodada: 2,
    grupo: 27,
    matricula: 2425,
    nome: 'Guilherme Morais Lopes Dos Santos',
  },
  {
    rodada: 2,
    grupo: 27,
    matricula: 2356,
    nome: 'Ana Paula De Souza Marques',
  },
  {
    rodada: 2,
    grupo: 27,
    matricula: 2432,
    nome: 'Rafaela Angelon',
  },
  {
    rodada: 2,
    grupo: 28,
    matricula: 2385,
    nome: 'Erika Burei Alves',
  },
  {
    rodada: 2,
    grupo: 28,
    matricula: 2355,
    nome: 'Luana Mara Dalla Costa',
  },
  {
    rodada: 2,
    grupo: 28,
    matricula: 2491,
    nome: 'Alison Hudson De Souza',
  },
  {
    rodada: 2,
    grupo: 28,
    matricula: 2393,
    nome: 'João Pedro Picolo',
  },
  {
    rodada: 2,
    grupo: 29,
    matricula: 2495,
    nome: 'Gustavo Dos Santos Polido',
  },
  {
    rodada: 2,
    grupo: 29,
    matricula: 2363,
    nome: 'Natália Schueda Menezes',
  },
  {
    rodada: 2,
    grupo: 29,
    matricula: 2349,
    nome: 'Rafael Matheus Chaves Silveira',
  },
  {
    rodada: 2,
    grupo: 29,
    matricula: 2474,
    nome: 'Sali Goretti Stocco',
  },
  {
    rodada: 2,
    grupo: 30,
    matricula: 2391,
    nome: 'Lígia Naomi Nakase',
  },
  {
    rodada: 2,
    grupo: 30,
    matricula: 2388,
    nome: 'Katherine Finn Zander',
  },
  {
    rodada: 2,
    grupo: 30,
    matricula: 2468,
    nome: 'Márcio José Gurka Júnior',
  },
  {
    rodada: 2,
    grupo: 30,
    matricula: 2426,
    nome: 'Matheus Teixeira Souza',
  },
  {
    rodada: 2,
    grupo: 31,
    matricula: 2492,
    nome: 'Luiz Siqueira',
  },
  {
    rodada: 2,
    grupo: 31,
    matricula: 2435,
    nome: 'Suzy Shiori Sakano',
  },
  {
    rodada: 2,
    grupo: 31,
    matricula: 2438,
    nome: 'Yasmin Mayer',
  },
  {
    rodada: 2,
    grupo: 31,
    matricula: 2350,
    nome: 'Alessandro Maciel Schmidt',
  },
  {
    rodada: 2,
    grupo: 32,
    matricula: 2508,
    nome: 'Victor Henrique De Moura Netto',
  },
  {
    rodada: 2,
    grupo: 32,
    matricula: 2389,
    nome: 'Eduardo Vinicius Schroeder',
  },
  {
    rodada: 2,
    grupo: 32,
    matricula: 2381,
    nome: 'Melissa Fernanda Rodrigues Siqueira',
  },
  {
    rodada: 2,
    grupo: 32,
    matricula: 2405,
    nome: 'Bruna Martins De Oliveira',
  },
  {
    rodada: 2,
    grupo: 33,
    matricula: 2354,
    nome: 'Leandro Allysson Joo',
  },
  {
    rodada: 2,
    grupo: 33,
    matricula: 2453,
    nome: 'Ana Paula Vieira Roviero',
  },
  {
    rodada: 2,
    grupo: 33,
    matricula: 2513,
    nome: 'Pedro Henrique Cordeiro Soares',
  },
  {
    rodada: 2,
    grupo: 33,
    matricula: 2379,
    nome: 'Cássia Megumi Fuku Oban',
  },
  {
    rodada: 2,
    grupo: 34,
    matricula: 2527,
    nome: 'Pedro Fernando Martins',
  },
  {
    rodada: 2,
    grupo: 34,
    matricula: 2488,
    nome: 'Paulo Tadashi Tokikawa',
  },
  {
    rodada: 2,
    grupo: 34,
    matricula: 2428,
    nome: 'Iara Curcio Fadel',
  },
  {
    rodada: 2,
    grupo: 34,
    matricula: 2373,
    nome: 'Ianca Polizelo',
  },
  {
    rodada: 2,
    grupo: 35,
    matricula: 2493,
    nome: 'Guilherme Pinho Gomig',
  },
  {
    rodada: 2,
    grupo: 35,
    matricula: 2467,
    nome: 'Flavia Lombardi Maceira',
  },
  {
    rodada: 2,
    grupo: 35,
    matricula: 2399,
    nome: 'Raul Gomes Pimentel De Almeida',
  },
  {
    rodada: 2,
    grupo: 35,
    matricula: 2410,
    nome: 'Milena Almeida De Menezes Caldas',
  },
  {
    rodada: 2,
    grupo: 36,
    matricula: 2461,
    nome: 'Kimberlly Hapuque Da Silva Brito',
  },
  {
    rodada: 2,
    grupo: 36,
    matricula: 2458,
    nome: 'Stefany Jardim Rodrigues',
  },
  {
    rodada: 2,
    grupo: 36,
    matricula: 2398,
    nome: 'Marlon Griebeler Da Hora',
  },
  {
    rodada: 2,
    grupo: 36,
    matricula: 2514,
    nome: 'Pedro Henrique Schisler Squisati',
  },
  {
    rodada: 2,
    grupo: 37,
    matricula: 2420,
    nome: 'Mônica Falat Reva Dell Agnolo',
  },
  {
    rodada: 2,
    grupo: 37,
    matricula: 2479,
    nome: 'Alis Eugenio Frentzel',
  },
  {
    rodada: 2,
    grupo: 37,
    matricula: 2358,
    nome: 'Hamilton Wanderson Fortes De Menezes',
  },
  {
    rodada: 2,
    grupo: 37,
    matricula: 2374,
    nome: 'Lucas Otavio Mariano Pinheiro Oro',
  },
  {
    rodada: 2,
    grupo: 38,
    matricula: 2446,
    nome: 'Felipe Alves Barboza',
  },
  {
    rodada: 2,
    grupo: 38,
    matricula: 2454,
    nome: 'Maria Luiza Santos Do Amaral',
  },
  {
    rodada: 2,
    grupo: 38,
    matricula: 2480,
    nome: 'Alexandra Dos Santos Gropp',
  },
  {
    rodada: 2,
    grupo: 38,
    matricula: 2414,
    nome: 'Marco Antônio Barbosa Zulian',
  },
  {
    rodada: 2,
    grupo: 39,
    matricula: 2470,
    nome: 'Weslley Felipe De Siqueira Dos Santos',
  },
  {
    rodada: 2,
    grupo: 39,
    matricula: 2401,
    nome: 'Barbara Cristina Xavier',
  },
  {
    rodada: 2,
    grupo: 39,
    matricula: 2378,
    nome: 'Sthefanny Ferreira Gonzaga',
  },
  {
    rodada: 2,
    grupo: 39,
    matricula: 2504,
    nome: 'André Luís Arns Guimarães',
  },
  {
    rodada: 2,
    grupo: 40,
    matricula: 2366,
    nome: 'Maria Teresa Kravetz Andrioli',
  },
  {
    rodada: 2,
    grupo: 40,
    matricula: 2359,
    nome: 'Alessandra Fernandes Lacerda',
  },
  {
    rodada: 2,
    grupo: 40,
    matricula: 2376,
    nome: 'Samuel Eberhardt',
  },
  {
    rodada: 2,
    grupo: 40,
    matricula: 2482,
    nome: 'Guilherme Barbosa Candido',
  },
  {
    rodada: 2,
    grupo: 41,
    matricula: 2494,
    nome: 'Arthur Giacobbe Kusma De Pauli',
  },
  {
    rodada: 2,
    grupo: 41,
    matricula: 2367,
    nome: 'Hanna Paterno Coutinho Ferreira',
  },
  {
    rodada: 2,
    grupo: 41,
    matricula: 2450,
    nome: 'Henrique Castro Santos',
  },
  {
    rodada: 2,
    grupo: 41,
    matricula: 2443,
    nome: 'Natalia Seixas Dias',
  },
  {
    rodada: 2,
    grupo: 42,
    matricula: 2484,
    nome: 'Filipe Xavier Melnik',
  },
  {
    rodada: 2,
    grupo: 42,
    matricula: 2365,
    nome: 'Caroline Revay Franciosi',
  },
  {
    rodada: 2,
    grupo: 42,
    matricula: 2353,
    nome: 'Alex Freitas Soares',
  },
  {
    rodada: 2,
    grupo: 42,
    matricula: 2419,
    nome: 'Marina De Domenico Salioni Dubuc',
  },
  {
    rodada: 2,
    grupo: 43,
    matricula: 2362,
    nome: 'Gustavo Monkolski Tatarem',
  },
  {
    rodada: 2,
    grupo: 43,
    matricula: 2404,
    nome: 'Eduardo Cristiano Franco',
  },
  {
    rodada: 2,
    grupo: 43,
    matricula: 2521,
    nome: 'Bruno Padovan Soares De Souza',
  },
  {
    rodada: 2,
    grupo: 43,
    matricula: 2469,
    nome: 'Lucas Yoshio Nakano',
  },
  {
    rodada: 2,
    grupo: 44,
    matricula: 2516,
    nome: 'William Schineider Rabelo',
  },
  {
    rodada: 2,
    grupo: 44,
    matricula: 2490,
    nome: 'Gustavo Esteves Fernandes',
  },
  {
    rodada: 2,
    grupo: 44,
    matricula: 2512,
    nome: 'Pablo Enrique Harbar Penas',
  },
  {
    rodada: 2,
    grupo: 44,
    matricula: 2375,
    nome: 'Jonathas Andrade Torquato',
  },
  {
    rodada: 2,
    grupo: 45,
    matricula: 2451,
    nome: 'Enzo Trevisan Topanotti',
  },
  {
    rodada: 2,
    grupo: 45,
    matricula: 2352,
    nome: 'Saulo Alberto Cintra Roseiro Junior',
  },
  {
    rodada: 2,
    grupo: 45,
    matricula: 2497,
    nome: 'Pietro Ricardo Schoch Alves',
  },
  {
    rodada: 2,
    grupo: 45,
    matricula: 2489,
    nome: 'Eduardo Batistel Zaniol',
  },
  {
    rodada: 3,
    grupo: 1,
    matricula: 2394,
    nome: 'Mariana Florencio De Oliveira',
  },
  {
    rodada: 3,
    grupo: 1,
    matricula: 2476,
    nome: 'Bruna Rodrigues Gazal Rocha',
  },
  {
    rodada: 3,
    grupo: 1,
    matricula: 2466,
    nome: 'Elliot Sabidussi',
  },
  {
    rodada: 3,
    grupo: 2,
    matricula: 2436,
    nome: 'Maria Teresa Ferreira Lima De Almeida',
  },
  {
    rodada: 3,
    grupo: 2,
    matricula: 2400,
    nome: 'Murilo Henrique Ghignatti',
  },
  {
    rodada: 3,
    grupo: 2,
    matricula: 2515,
    nome: 'Filipe Scorsin Cercal',
  },
  {
    rodada: 3,
    grupo: 2,
    matricula: 2385,
    nome: 'Erika Burei Alves',
  },
  {
    rodada: 3,
    grupo: 3,
    matricula: 2434,
    nome: 'Ana Bittencourt Vidigal',
  },
  {
    rodada: 3,
    grupo: 3,
    matricula: 2496,
    nome: 'Vitor Aguiar Treglia',
  },
  {
    rodada: 3,
    grupo: 3,
    matricula: 2372,
    nome: 'Gabriel Torres Andreassa',
  },
  {
    rodada: 3,
    grupo: 3,
    matricula: 2454,
    nome: 'Maria Luiza Santos Do Amaral',
  },
  {
    rodada: 3,
    grupo: 4,
    matricula: 2509,
    nome: 'Cesar André Costa Vaz',
  },
  {
    rodada: 3,
    grupo: 4,
    matricula: 2417,
    nome: 'Luísa Bacichett Trabulci',
  },
  {
    rodada: 3,
    grupo: 4,
    matricula: 2383,
    nome: 'Alessandra Souza Da Silva',
  },
  {
    rodada: 3,
    grupo: 4,
    matricula: 2523,
    nome: 'Aruni Serena Van Amstel',
  },
  {
    rodada: 3,
    grupo: 5,
    matricula: 2368,
    nome: 'Bruna Naomi Yamanaka Silva',
  },
  {
    rodada: 3,
    grupo: 5,
    matricula: 2498,
    nome: 'Levy Gomes Dos Santos Neto',
  },
  {
    rodada: 3,
    grupo: 5,
    matricula: 2421,
    nome: 'Ianara De Souza Maldaner',
  },
  {
    rodada: 3,
    grupo: 5,
    matricula: 2389,
    nome: 'Eduardo Vinicius Schroeder',
  },
  {
    rodada: 3,
    grupo: 6,
    matricula: 2510,
    nome: 'Julio Teixeira Bojan',
  },
  {
    rodada: 3,
    grupo: 6,
    matricula: 2449,
    nome: 'Isabela Luiza Molin De Siqueira',
  },
  {
    rodada: 3,
    grupo: 6,
    matricula: 2370,
    nome: 'Djenifer Renata Pereira',
  },
  {
    rodada: 3,
    grupo: 6,
    matricula: 2524,
    nome: 'Rodrigo Villas Boas Petroni',
  },
  {
    rodada: 3,
    grupo: 7,
    matricula: 2430,
    nome: 'Larissa Paschoalin',
  },
  {
    rodada: 3,
    grupo: 7,
    matricula: 2465,
    nome: 'Matheus Henrique Tambosi',
  },
  {
    rodada: 3,
    grupo: 7,
    matricula: 2371,
    nome: 'Andrea Alexandra Sánez Oquendo',
  },
  {
    rodada: 3,
    grupo: 7,
    matricula: 2354,
    nome: 'Leandro Allysson Joo',
  },
  {
    rodada: 3,
    grupo: 8,
    matricula: 2422,
    nome: 'Raquel Daleffi Zocoler',
  },
  {
    rodada: 3,
    grupo: 8,
    matricula: 2462,
    nome: 'Renato Ferreira Godinho',
  },
  {
    rodada: 3,
    grupo: 8,
    matricula: 2403,
    nome: 'João Gustavo Król',
  },
  {
    rodada: 3,
    grupo: 8,
    matricula: 2395,
    nome: 'Giulia Andreazza Amaral',
  },
  {
    rodada: 3,
    grupo: 9,
    matricula: 2448,
    nome: 'Gabriel Vieira Rodrigues',
  },
  {
    rodada: 3,
    grupo: 9,
    matricula: 2518,
    nome: 'Frederico Westphalen Mendes Machado',
  },
  {
    rodada: 3,
    grupo: 9,
    matricula: 2472,
    nome: 'Amanda Lisboa',
  },
  {
    rodada: 3,
    grupo: 9,
    matricula: 2365,
    nome: 'Caroline Revay Franciosi',
  },
  {
    rodada: 3,
    grupo: 10,
    matricula: 2390,
    nome: 'Marcus Augusto Ferreira Dudeque',
  },
  {
    rodada: 3,
    grupo: 10,
    matricula: 2406,
    nome: 'Helen Skorupski Sloboda',
  },
  {
    rodada: 3,
    grupo: 10,
    matricula: 2520,
    nome: 'Leonardo Barbosa Burgomeister',
  },
  {
    rodada: 3,
    grupo: 10,
    matricula: 2369,
    nome: 'Kauane Santana Da Rosa',
  },
  {
    rodada: 3,
    grupo: 11,
    matricula: 2463,
    nome: 'Francisco Lucas Rezende',
  },
  {
    rodada: 3,
    grupo: 11,
    matricula: 2447,
    nome: 'Ana Luisa Duda Stege',
  },
  {
    rodada: 3,
    grupo: 11,
    matricula: 2475,
    nome: 'Geovanna Kasemirinski Da Silva',
  },
  {
    rodada: 3,
    grupo: 11,
    matricula: 2444,
    nome: 'Thiago Henrique Xavier Medeiros',
  },
  {
    rodada: 3,
    grupo: 12,
    matricula: 2485,
    nome: 'Gabriel Puppi Gozzo',
  },
  {
    rodada: 3,
    grupo: 12,
    matricula: 2416,
    nome: 'Giovana Garcia Ribeiro',
  },
  {
    rodada: 3,
    grupo: 12,
    matricula: 2526,
    nome: 'Guilerme Moreira Ribeiro Barciki',
  },
  {
    rodada: 3,
    grupo: 12,
    matricula: 2412,
    nome: 'Jéssica Akemi Meguro',
  },
  {
    rodada: 3,
    grupo: 13,
    matricula: 2360,
    nome: 'Mario Morais Neto',
  },
  {
    rodada: 3,
    grupo: 13,
    matricula: 2478,
    nome: 'Bianca De Oliveira Brecailo',
  },
  {
    rodada: 3,
    grupo: 13,
    matricula: 2500,
    nome: 'Lucas Pereira Luiz',
  },
  {
    rodada: 3,
    grupo: 13,
    matricula: 2464,
    nome: 'Isabela Martin Silva',
  },
  {
    rodada: 3,
    grupo: 14,
    matricula: 2481,
    nome: 'Bruno Yuiti Leão Imai',
  },
  {
    rodada: 3,
    grupo: 14,
    matricula: 2431,
    nome: 'Barbra Eliza Domingues Da Silva',
  },
  {
    rodada: 3,
    grupo: 14,
    matricula: 2452,
    nome: 'Isabela Amanda Ciuneck',
  },
  {
    rodada: 3,
    grupo: 14,
    matricula: 2495,
    nome: 'Gustavo Dos Santos Polido',
  },
  {
    rodada: 3,
    grupo: 15,
    matricula: 2439,
    nome: 'Jady Torralvo Alves',
  },
  {
    rodada: 3,
    grupo: 15,
    matricula: 2522,
    nome: 'Diogo Andreatta Bergamo',
  },
  {
    rodada: 3,
    grupo: 15,
    matricula: 2382,
    nome: 'Fernanda Mayumi Obayashi',
  },
  {
    rodada: 3,
    grupo: 15,
    matricula: 2517,
    nome: 'Jean Ricardo Grein',
  },
  {
    rodada: 3,
    grupo: 16,
    matricula: 2361,
    nome: 'Leonardo José Zanotti',
  },
  {
    rodada: 3,
    grupo: 16,
    matricula: 2459,
    nome: 'Felipe Seolin Bento',
  },
  {
    rodada: 3,
    grupo: 16,
    matricula: 2384,
    nome: 'Gabriela Bogomolof Taquegami',
  },
  {
    rodada: 3,
    grupo: 16,
    matricula: 2473,
    nome: 'Laís Affornali Fernandes',
  },
  {
    rodada: 3,
    grupo: 17,
    matricula: 2433,
    nome: 'Ingrid Vitória Giese',
  },
  {
    rodada: 3,
    grupo: 17,
    matricula: 2502,
    nome: 'Carlos Augusto Toledo Martins',
  },
  {
    rodada: 3,
    grupo: 17,
    matricula: 2397,
    nome: 'Eduardo Rosso Barbosa',
  },
  {
    rodada: 3,
    grupo: 17,
    matricula: 2401,
    nome: 'Barbara Cristina Xavier',
  },
  {
    rodada: 3,
    grupo: 18,
    matricula: 2487,
    nome: 'Alisson Rizzi Kuzjman',
  },
  {
    rodada: 3,
    grupo: 18,
    matricula: 2402,
    nome: 'Deborah Eberle Dos Santos',
  },
  {
    rodada: 3,
    grupo: 18,
    matricula: 2392,
    nome: 'Ana Carolina De Souza Costa',
  },
  {
    rodada: 3,
    grupo: 18,
    matricula: 2377,
    nome: 'Oswaldo Da Silva Schermach',
  },
  {
    rodada: 3,
    grupo: 19,
    matricula: 2380,
    nome: 'Julia Zimmermann Cordeiro',
  },
  {
    rodada: 3,
    grupo: 19,
    matricula: 2525,
    nome: 'André Shizuo Hachiguti De Quadros',
  },
  {
    rodada: 3,
    grupo: 19,
    matricula: 2427,
    nome: 'Naomi Nakanishi Frigotto',
  },
  {
    rodada: 3,
    grupo: 19,
    matricula: 2357,
    nome: 'Mateus Maidel Alves Da Silva',
  },
  {
    rodada: 3,
    grupo: 20,
    matricula: 2364,
    nome: 'Isabela Makiolka Montingelli',
  },
  {
    rodada: 3,
    grupo: 20,
    matricula: 2437,
    nome: 'Natalia Da Rosa',
  },
  {
    rodada: 3,
    grupo: 20,
    matricula: 2501,
    nome: 'Eros Maurilio De Oliveira Silvio Doro Pereira',
  },
  {
    rodada: 3,
    grupo: 20,
    matricula: 2527,
    nome: 'Pedro Fernando Martins',
  },
  {
    rodada: 3,
    grupo: 21,
    matricula: 2429,
    nome: 'Bianca De Fatima Scharneski',
  },
  {
    rodada: 3,
    grupo: 21,
    matricula: 2386,
    nome: 'Eloísa De Oliveira Almeida',
  },
  {
    rodada: 3,
    grupo: 21,
    matricula: 2415,
    nome: 'Lucas Augusto De Castro Coelho',
  },
  {
    rodada: 3,
    grupo: 21,
    matricula: 2483,
    nome: 'Erick Martins Do Nascimento',
  },
  {
    rodada: 3,
    grupo: 22,
    matricula: 2348,
    nome: 'Bernardo Augusto Monteiro De Oliveira Klingelfus',
  },
  {
    rodada: 3,
    grupo: 22,
    matricula: 2423,
    nome: 'Daniella Onishi',
  },
  {
    rodada: 3,
    grupo: 22,
    matricula: 2456,
    nome: 'Carolina Martins Gonçalves',
  },
  {
    rodada: 3,
    grupo: 22,
    matricula: 2503,
    nome: 'Bernardo Dos Reis De Melo',
  },
  {
    rodada: 3,
    grupo: 23,
    matricula: 2506,
    nome: 'Vinícius Couto Tasso',
  },
  {
    rodada: 3,
    grupo: 23,
    matricula: 2471,
    nome: 'Isabella Buzanello Martins',
  },
  {
    rodada: 3,
    grupo: 23,
    matricula: 2396,
    nome: 'Ana Paula Kessler Gonçalves',
  },
  {
    rodada: 3,
    grupo: 23,
    matricula: 2494,
    nome: 'Arthur Giacobbe Kusma De Pauli',
  },
  {
    rodada: 3,
    grupo: 24,
    matricula: 2455,
    nome: 'Fabiana Martins Budel',
  },
  {
    rodada: 3,
    grupo: 24,
    matricula: 2507,
    nome: 'Gustavo Kumasawa',
  },
  {
    rodada: 3,
    grupo: 24,
    matricula: 2424,
    nome: 'João Carlos Delay Junior',
  },
  {
    rodada: 3,
    grupo: 24,
    matricula: 2457,
    nome: 'Alessandra Boscardin Aver',
  },
  {
    rodada: 3,
    grupo: 25,
    matricula: 2486,
    nome: 'Emerson Fabiano Marques Junior',
  },
  {
    rodada: 3,
    grupo: 25,
    matricula: 2418,
    nome: 'Danielly J. P. Lazaro',
  },
  {
    rodada: 3,
    grupo: 25,
    matricula: 2477,
    nome: 'Fernanda Alves Martinhaki',
  },
  {
    rodada: 3,
    grupo: 25,
    matricula: 2511,
    nome: 'Herivelton José Gomes Da Trindade Júnior',
  },
  {
    rodada: 3,
    grupo: 26,
    matricula: 2460,
    nome: 'Tacila Fernanda Carneiro Evangelista',
  },
  {
    rodada: 3,
    grupo: 26,
    matricula: 2519,
    nome: 'Murilo Vidal',
  },
  {
    rodada: 3,
    grupo: 26,
    matricula: 2440,
    nome: 'Natália Grein Silva',
  },
  {
    rodada: 3,
    grupo: 26,
    matricula: 2505,
    nome: 'André Schueda Menezes',
  },
  {
    rodada: 3,
    grupo: 27,
    matricula: 2425,
    nome: 'Guilherme Morais Lopes Dos Santos',
  },
  {
    rodada: 3,
    grupo: 27,
    matricula: 2356,
    nome: 'Ana Paula De Souza Marques',
  },
  {
    rodada: 3,
    grupo: 27,
    matricula: 2432,
    nome: 'Rafaela Angelon',
  },
  {
    rodada: 3,
    grupo: 27,
    matricula: 2351,
    nome: 'Rogério Bayer Ghizi',
  },
  {
    rodada: 3,
    grupo: 28,
    matricula: 2355,
    nome: 'Luana Mara Dalla Costa',
  },
  {
    rodada: 3,
    grupo: 28,
    matricula: 2491,
    nome: 'Alison Hudson De Souza',
  },
  {
    rodada: 3,
    grupo: 28,
    matricula: 2393,
    nome: 'João Pedro Picolo',
  },
  {
    rodada: 3,
    grupo: 28,
    matricula: 2391,
    nome: 'Lígia Naomi Nakase',
  },
  {
    rodada: 3,
    grupo: 29,
    matricula: 2363,
    nome: 'Natália Schueda Menezes',
  },
  {
    rodada: 3,
    grupo: 29,
    matricula: 2349,
    nome: 'Rafael Matheus Chaves Silveira',
  },
  {
    rodada: 3,
    grupo: 29,
    matricula: 2474,
    nome: 'Sali Goretti Stocco',
  },
  {
    rodada: 3,
    grupo: 29,
    matricula: 2490,
    nome: 'Gustavo Esteves Fernandes',
  },
  {
    rodada: 3,
    grupo: 30,
    matricula: 2388,
    nome: 'Katherine Finn Zander',
  },
  {
    rodada: 3,
    grupo: 30,
    matricula: 2468,
    nome: 'Márcio José Gurka Júnior',
  },
  {
    rodada: 3,
    grupo: 30,
    matricula: 2426,
    nome: 'Matheus Teixeira Souza',
  },
  {
    rodada: 3,
    grupo: 30,
    matricula: 2441,
    nome: 'Letícia Vallejo Zaranski',
  },
  {
    rodada: 3,
    grupo: 31,
    matricula: 2435,
    nome: 'Suzy Shiori Sakano',
  },
  {
    rodada: 3,
    grupo: 31,
    matricula: 2438,
    nome: 'Yasmin Mayer',
  },
  {
    rodada: 3,
    grupo: 31,
    matricula: 2350,
    nome: 'Alessandro Maciel Schmidt',
  },
  {
    rodada: 3,
    grupo: 31,
    matricula: 2411,
    nome: 'João Vitor Moreira',
  },
  {
    rodada: 3,
    grupo: 32,
    matricula: 2508,
    nome: 'Victor Henrique De Moura Netto',
  },
  {
    rodada: 3,
    grupo: 32,
    matricula: 2381,
    nome: 'Melissa Fernanda Rodrigues Siqueira',
  },
  {
    rodada: 3,
    grupo: 32,
    matricula: 2405,
    nome: 'Bruna Martins De Oliveira',
  },
  {
    rodada: 3,
    grupo: 32,
    matricula: 2407,
    nome: 'Bruno Siedekum Thuma',
  },
  {
    rodada: 3,
    grupo: 33,
    matricula: 2453,
    nome: 'Ana Paula Vieira Roviero',
  },
  {
    rodada: 3,
    grupo: 33,
    matricula: 2513,
    nome: 'Pedro Henrique Cordeiro Soares',
  },
  {
    rodada: 3,
    grupo: 33,
    matricula: 2379,
    nome: 'Cássia Megumi Fuku Oban',
  },
  {
    rodada: 3,
    grupo: 33,
    matricula: 2499,
    nome: 'Neidivaldo Dias Da Silva Junior',
  },
  {
    rodada: 3,
    grupo: 34,
    matricula: 2488,
    nome: 'Paulo Tadashi Tokikawa',
  },
  {
    rodada: 3,
    grupo: 34,
    matricula: 2428,
    nome: 'Iara Curcio Fadel',
  },
  {
    rodada: 3,
    grupo: 34,
    matricula: 2373,
    nome: 'Ianca Polizelo',
  },
  {
    rodada: 3,
    grupo: 34,
    matricula: 2409,
    nome: 'Alan Renato Bunese',
  },
  {
    rodada: 3,
    grupo: 35,
    matricula: 2493,
    nome: 'Guilherme Pinho Gomig',
  },
  {
    rodada: 3,
    grupo: 35,
    matricula: 2399,
    nome: 'Raul Gomes Pimentel De Almeida',
  },
  {
    rodada: 3,
    grupo: 35,
    matricula: 2410,
    nome: 'Milena Almeida De Menezes Caldas',
  },
  {
    rodada: 3,
    grupo: 35,
    matricula: 2408,
    nome: 'Gabriele Batista Do Nascimento',
  },
  {
    rodada: 3,
    grupo: 36,
    matricula: 2458,
    nome: 'Stefany Jardim Rodrigues',
  },
  {
    rodada: 3,
    grupo: 36,
    matricula: 2398,
    nome: 'Marlon Griebeler Da Hora',
  },
  {
    rodada: 3,
    grupo: 36,
    matricula: 2514,
    nome: 'Pedro Henrique Schisler Squisati',
  },
  {
    rodada: 3,
    grupo: 36,
    matricula: 2467,
    nome: 'Flavia Lombardi Maceira',
  },
  {
    rodada: 3,
    grupo: 37,
    matricula: 2479,
    nome: 'Alis Eugenio Frentzel',
  },
  {
    rodada: 3,
    grupo: 37,
    matricula: 2358,
    nome: 'Hamilton Wanderson Fortes De Menezes',
  },
  {
    rodada: 3,
    grupo: 37,
    matricula: 2374,
    nome: 'Lucas Otavio Mariano Pinheiro Oro',
  },
  {
    rodada: 3,
    grupo: 37,
    matricula: 2461,
    nome: 'Kimberlly Hapuque Da Silva Brito',
  },
  {
    rodada: 3,
    grupo: 38,
    matricula: 2446,
    nome: 'Felipe Alves Barboza',
  },
  {
    rodada: 3,
    grupo: 38,
    matricula: 2480,
    nome: 'Alexandra Dos Santos Gropp',
  },
  {
    rodada: 3,
    grupo: 38,
    matricula: 2414,
    nome: 'Marco Antônio Barbosa Zulian',
  },
  {
    rodada: 3,
    grupo: 38,
    matricula: 2413,
    nome: 'Letícia Camargo De Sá Silva',
  },
  {
    rodada: 3,
    grupo: 39,
    matricula: 2470,
    nome: 'Weslley Felipe De Siqueira Dos Santos',
  },
  {
    rodada: 3,
    grupo: 39,
    matricula: 2378,
    nome: 'Sthefanny Ferreira Gonzaga',
  },
  {
    rodada: 3,
    grupo: 39,
    matricula: 2504,
    nome: 'André Luís Arns Guimarães',
  },
  {
    rodada: 3,
    grupo: 39,
    matricula: 2359,
    nome: 'Alessandra Fernandes Lacerda',
  },
  {
    rodada: 3,
    grupo: 40,
    matricula: 2366,
    nome: 'Maria Teresa Kravetz Andrioli',
  },
  {
    rodada: 3,
    grupo: 40,
    matricula: 2376,
    nome: 'Samuel Eberhardt',
  },
  {
    rodada: 3,
    grupo: 40,
    matricula: 2482,
    nome: 'Guilherme Barbosa Candido',
  },
  {
    rodada: 3,
    grupo: 40,
    matricula: 2442,
    nome: 'Isadora Rossetto Nogueira Drummond',
  },
  {
    rodada: 3,
    grupo: 41,
    matricula: 2367,
    nome: 'Hanna Paterno Coutinho Ferreira',
  },
  {
    rodada: 3,
    grupo: 41,
    matricula: 2450,
    nome: 'Henrique Castro Santos',
  },
  {
    rodada: 3,
    grupo: 41,
    matricula: 2443,
    nome: 'Natalia Seixas Dias',
  },
  {
    rodada: 3,
    grupo: 41,
    matricula: 2404,
    nome: 'Eduardo Cristiano Franco',
  },
  {
    rodada: 3,
    grupo: 42,
    matricula: 2484,
    nome: 'Filipe Xavier Melnik',
  },
  {
    rodada: 3,
    grupo: 42,
    matricula: 2353,
    nome: 'Alex Freitas Soares',
  },
  {
    rodada: 3,
    grupo: 42,
    matricula: 2419,
    nome: 'Marina De Domenico Salioni Dubuc',
  },
  {
    rodada: 3,
    grupo: 42,
    matricula: 2420,
    nome: 'Mônica Falat Reva Dell Agnolo',
  },
  {
    rodada: 3,
    grupo: 43,
    matricula: 2362,
    nome: 'Gustavo Monkolski Tatarem',
  },
  {
    rodada: 3,
    grupo: 43,
    matricula: 2521,
    nome: 'Bruno Padovan Soares De Souza',
  },
  {
    rodada: 3,
    grupo: 43,
    matricula: 2469,
    nome: 'Lucas Yoshio Nakano',
  },
  {
    rodada: 3,
    grupo: 43,
    matricula: 2445,
    nome: 'Matheus Dos Santos Pedrozo De Lima',
  },
  {
    rodada: 3,
    grupo: 44,
    matricula: 2516,
    nome: 'William Schineider Rabelo',
  },
  {
    rodada: 3,
    grupo: 44,
    matricula: 2512,
    nome: 'Pablo Enrique Harbar Penas',
  },
  {
    rodada: 3,
    grupo: 44,
    matricula: 2375,
    nome: 'Jonathas Andrade Torquato',
  },
  {
    rodada: 3,
    grupo: 44,
    matricula: 2451,
    nome: 'Enzo Trevisan Topanotti',
  },
  {
    rodada: 3,
    grupo: 45,
    matricula: 2352,
    nome: 'Saulo Alberto Cintra Roseiro Junior',
  },
  {
    rodada: 3,
    grupo: 45,
    matricula: 2497,
    nome: 'Pietro Ricardo Schoch Alves',
  },
  {
    rodada: 3,
    grupo: 45,
    matricula: 2489,
    nome: 'Eduardo Batistel Zaniol',
  },
  {
    rodada: 3,
    grupo: 45,
    matricula: 2492,
    nome: 'Luiz Siqueira',
  },
  {
    rodada: 4,
    grupo: 1,
    matricula: 2476,
    nome: 'Bruna Rodrigues Gazal Rocha',
  },
  {
    rodada: 4,
    grupo: 1,
    matricula: 2466,
    nome: 'Elliot Sabidussi',
  },
  {
    rodada: 4,
    grupo: 1,
    matricula: 2367,
    nome: 'Hanna Paterno Coutinho Ferreira',
  },
  {
    rodada: 4,
    grupo: 2,
    matricula: 2400,
    nome: 'Murilo Henrique Ghignatti',
  },
  {
    rodada: 4,
    grupo: 2,
    matricula: 2515,
    nome: 'Filipe Scorsin Cercal',
  },
  {
    rodada: 4,
    grupo: 2,
    matricula: 2385,
    nome: 'Erika Burei Alves',
  },
  {
    rodada: 4,
    grupo: 2,
    matricula: 2394,
    nome: 'Mariana Florencio De Oliveira',
  },
  {
    rodada: 4,
    grupo: 3,
    matricula: 2496,
    nome: 'Vitor Aguiar Treglia',
  },
  {
    rodada: 4,
    grupo: 3,
    matricula: 2372,
    nome: 'Gabriel Torres Andreassa',
  },
  {
    rodada: 4,
    grupo: 3,
    matricula: 2454,
    nome: 'Maria Luiza Santos Do Amaral',
  },
  {
    rodada: 4,
    grupo: 3,
    matricula: 2368,
    nome: 'Bruna Naomi Yamanaka Silva',
  },
  {
    rodada: 4,
    grupo: 4,
    matricula: 2417,
    nome: 'Luísa Bacichett Trabulci',
  },
  {
    rodada: 4,
    grupo: 4,
    matricula: 2383,
    nome: 'Alessandra Souza Da Silva',
  },
  {
    rodada: 4,
    grupo: 4,
    matricula: 2523,
    nome: 'Aruni Serena Van Amstel',
  },
  {
    rodada: 4,
    grupo: 4,
    matricula: 2484,
    nome: 'Filipe Xavier Melnik',
  },
  {
    rodada: 4,
    grupo: 5,
    matricula: 2498,
    nome: 'Levy Gomes Dos Santos Neto',
  },
  {
    rodada: 4,
    grupo: 5,
    matricula: 2421,
    nome: 'Ianara De Souza Maldaner',
  },
  {
    rodada: 4,
    grupo: 5,
    matricula: 2389,
    nome: 'Eduardo Vinicius Schroeder',
  },
  {
    rodada: 4,
    grupo: 5,
    matricula: 2380,
    nome: 'Julia Zimmermann Cordeiro',
  },
  {
    rodada: 4,
    grupo: 6,
    matricula: 2449,
    nome: 'Isabela Luiza Molin De Siqueira',
  },
  {
    rodada: 4,
    grupo: 6,
    matricula: 2370,
    nome: 'Djenifer Renata Pereira',
  },
  {
    rodada: 4,
    grupo: 6,
    matricula: 2524,
    nome: 'Rodrigo Villas Boas Petroni',
  },
  {
    rodada: 4,
    grupo: 6,
    matricula: 2509,
    nome: 'Cesar André Costa Vaz',
  },
  {
    rodada: 4,
    grupo: 7,
    matricula: 2465,
    nome: 'Matheus Henrique Tambosi',
  },
  {
    rodada: 4,
    grupo: 7,
    matricula: 2371,
    nome: 'Andrea Alexandra Sánez Oquendo',
  },
  {
    rodada: 4,
    grupo: 7,
    matricula: 2354,
    nome: 'Leandro Allysson Joo',
  },
  {
    rodada: 4,
    grupo: 7,
    matricula: 2436,
    nome: 'Maria Teresa Ferreira Lima De Almeida',
  },
  {
    rodada: 4,
    grupo: 8,
    matricula: 2462,
    nome: 'Renato Ferreira Godinho',
  },
  {
    rodada: 4,
    grupo: 8,
    matricula: 2403,
    nome: 'João Gustavo Król',
  },
  {
    rodada: 4,
    grupo: 8,
    matricula: 2395,
    nome: 'Giulia Andreazza Amaral',
  },
  {
    rodada: 4,
    grupo: 8,
    matricula: 2429,
    nome: 'Bianca De Fatima Scharneski',
  },
  {
    rodada: 4,
    grupo: 9,
    matricula: 2518,
    nome: 'Frederico Westphalen Mendes Machado',
  },
  {
    rodada: 4,
    grupo: 9,
    matricula: 2472,
    nome: 'Amanda Lisboa',
  },
  {
    rodada: 4,
    grupo: 9,
    matricula: 2365,
    nome: 'Caroline Revay Franciosi',
  },
  {
    rodada: 4,
    grupo: 9,
    matricula: 2390,
    nome: 'Marcus Augusto Ferreira Dudeque',
  },
  {
    rodada: 4,
    grupo: 10,
    matricula: 2406,
    nome: 'Helen Skorupski Sloboda',
  },
  {
    rodada: 4,
    grupo: 10,
    matricula: 2520,
    nome: 'Leonardo Barbosa Burgomeister',
  },
  {
    rodada: 4,
    grupo: 10,
    matricula: 2369,
    nome: 'Kauane Santana Da Rosa',
  },
  {
    rodada: 4,
    grupo: 10,
    matricula: 2448,
    nome: 'Gabriel Vieira Rodrigues',
  },
  {
    rodada: 4,
    grupo: 11,
    matricula: 2447,
    nome: 'Ana Luisa Duda Stege',
  },
  {
    rodada: 4,
    grupo: 11,
    matricula: 2475,
    nome: 'Geovanna Kasemirinski Da Silva',
  },
  {
    rodada: 4,
    grupo: 11,
    matricula: 2444,
    nome: 'Thiago Henrique Xavier Medeiros',
  },
  {
    rodada: 4,
    grupo: 11,
    matricula: 2493,
    nome: 'Guilherme Pinho Gomig',
  },
  {
    rodada: 4,
    grupo: 12,
    matricula: 2416,
    nome: 'Giovana Garcia Ribeiro',
  },
  {
    rodada: 4,
    grupo: 12,
    matricula: 2526,
    nome: 'Guilerme Moreira Ribeiro Barciki',
  },
  {
    rodada: 4,
    grupo: 12,
    matricula: 2412,
    nome: 'Jéssica Akemi Meguro',
  },
  {
    rodada: 4,
    grupo: 12,
    matricula: 2446,
    nome: 'Felipe Alves Barboza',
  },
  {
    rodada: 4,
    grupo: 13,
    matricula: 2478,
    nome: 'Bianca De Oliveira Brecailo',
  },
  {
    rodada: 4,
    grupo: 13,
    matricula: 2500,
    nome: 'Lucas Pereira Luiz',
  },
  {
    rodada: 4,
    grupo: 13,
    matricula: 2464,
    nome: 'Isabela Martin Silva',
  },
  {
    rodada: 4,
    grupo: 13,
    matricula: 2487,
    nome: 'Alisson Rizzi Kuzjman',
  },
  {
    rodada: 4,
    grupo: 14,
    matricula: 2431,
    nome: 'Barbra Eliza Domingues Da Silva',
  },
  {
    rodada: 4,
    grupo: 14,
    matricula: 2452,
    nome: 'Isabela Amanda Ciuneck',
  },
  {
    rodada: 4,
    grupo: 14,
    matricula: 2495,
    nome: 'Gustavo Dos Santos Polido',
  },
  {
    rodada: 4,
    grupo: 14,
    matricula: 2463,
    nome: 'Francisco Lucas Rezende',
  },
  {
    rodada: 4,
    grupo: 15,
    matricula: 2522,
    nome: 'Diogo Andreatta Bergamo',
  },
  {
    rodada: 4,
    grupo: 15,
    matricula: 2382,
    nome: 'Fernanda Mayumi Obayashi',
  },
  {
    rodada: 4,
    grupo: 15,
    matricula: 2517,
    nome: 'Jean Ricardo Grein',
  },
  {
    rodada: 4,
    grupo: 15,
    matricula: 2364,
    nome: 'Isabela Makiolka Montingelli',
  },
  {
    rodada: 4,
    grupo: 16,
    matricula: 2459,
    nome: 'Felipe Seolin Bento',
  },
  {
    rodada: 4,
    grupo: 16,
    matricula: 2384,
    nome: 'Gabriela Bogomolof Taquegami',
  },
  {
    rodada: 4,
    grupo: 16,
    matricula: 2473,
    nome: 'Laís Affornali Fernandes',
  },
  {
    rodada: 4,
    grupo: 16,
    matricula: 2470,
    nome: 'Weslley Felipe De Siqueira Dos Santos',
  },
  {
    rodada: 4,
    grupo: 17,
    matricula: 2502,
    nome: 'Carlos Augusto Toledo Martins',
  },
  {
    rodada: 4,
    grupo: 17,
    matricula: 2397,
    nome: 'Eduardo Rosso Barbosa',
  },
  {
    rodada: 4,
    grupo: 17,
    matricula: 2401,
    nome: 'Barbara Cristina Xavier',
  },
  {
    rodada: 4,
    grupo: 17,
    matricula: 2422,
    nome: 'Raquel Daleffi Zocoler',
  },
  {
    rodada: 4,
    grupo: 18,
    matricula: 2402,
    nome: 'Deborah Eberle Dos Santos',
  },
  {
    rodada: 4,
    grupo: 18,
    matricula: 2392,
    nome: 'Ana Carolina De Souza Costa',
  },
  {
    rodada: 4,
    grupo: 18,
    matricula: 2377,
    nome: 'Oswaldo Da Silva Schermach',
  },
  {
    rodada: 4,
    grupo: 18,
    matricula: 2352,
    nome: 'Saulo Alberto Cintra Roseiro Junior',
  },
  {
    rodada: 4,
    grupo: 19,
    matricula: 2525,
    nome: 'André Shizuo Hachiguti De Quadros',
  },
  {
    rodada: 4,
    grupo: 19,
    matricula: 2427,
    nome: 'Naomi Nakanishi Frigotto',
  },
  {
    rodada: 4,
    grupo: 19,
    matricula: 2357,
    nome: 'Mateus Maidel Alves Da Silva',
  },
  {
    rodada: 4,
    grupo: 19,
    matricula: 2439,
    nome: 'Jady Torralvo Alves',
  },
  {
    rodada: 4,
    grupo: 20,
    matricula: 2437,
    nome: 'Natalia Da Rosa',
  },
  {
    rodada: 4,
    grupo: 20,
    matricula: 2501,
    nome: 'Eros Maurilio De Oliveira Silvio Doro Pereira',
  },
  {
    rodada: 4,
    grupo: 20,
    matricula: 2527,
    nome: 'Pedro Fernando Martins',
  },
  {
    rodada: 4,
    grupo: 20,
    matricula: 2363,
    nome: 'Natália Schueda Menezes',
  },
  {
    rodada: 4,
    grupo: 21,
    matricula: 2386,
    nome: 'Eloísa De Oliveira Almeida',
  },
  {
    rodada: 4,
    grupo: 21,
    matricula: 2415,
    nome: 'Lucas Augusto De Castro Coelho',
  },
  {
    rodada: 4,
    grupo: 21,
    matricula: 2483,
    nome: 'Erick Martins Do Nascimento',
  },
  {
    rodada: 4,
    grupo: 21,
    matricula: 2434,
    nome: 'Ana Bittencourt Vidigal',
  },
  {
    rodada: 4,
    grupo: 22,
    matricula: 2423,
    nome: 'Daniella Onishi',
  },
  {
    rodada: 4,
    grupo: 22,
    matricula: 2456,
    nome: 'Carolina Martins Gonçalves',
  },
  {
    rodada: 4,
    grupo: 22,
    matricula: 2503,
    nome: 'Bernardo Dos Reis De Melo',
  },
  {
    rodada: 4,
    grupo: 22,
    matricula: 2486,
    nome: 'Emerson Fabiano Marques Junior',
  },
  {
    rodada: 4,
    grupo: 23,
    matricula: 2471,
    nome: 'Isabella Buzanello Martins',
  },
  {
    rodada: 4,
    grupo: 23,
    matricula: 2396,
    nome: 'Ana Paula Kessler Gonçalves',
  },
  {
    rodada: 4,
    grupo: 23,
    matricula: 2494,
    nome: 'Arthur Giacobbe Kusma De Pauli',
  },
  {
    rodada: 4,
    grupo: 23,
    matricula: 2481,
    nome: 'Bruno Yuiti Leão Imai',
  },
  {
    rodada: 4,
    grupo: 24,
    matricula: 2507,
    nome: 'Gustavo Kumasawa',
  },
  {
    rodada: 4,
    grupo: 24,
    matricula: 2424,
    nome: 'João Carlos Delay Junior',
  },
  {
    rodada: 4,
    grupo: 24,
    matricula: 2457,
    nome: 'Alessandra Boscardin Aver',
  },
  {
    rodada: 4,
    grupo: 24,
    matricula: 2388,
    nome: 'Katherine Finn Zander',
  },
  {
    rodada: 4,
    grupo: 25,
    matricula: 2418,
    nome: 'Danielly J. P. Lazaro',
  },
  {
    rodada: 4,
    grupo: 25,
    matricula: 2477,
    nome: 'Fernanda Alves Martinhaki',
  },
  {
    rodada: 4,
    grupo: 25,
    matricula: 2511,
    nome: 'Herivelton José Gomes Da Trindade Júnior',
  },
  {
    rodada: 4,
    grupo: 25,
    matricula: 2516,
    nome: 'William Schineider Rabelo',
  },
  {
    rodada: 4,
    grupo: 26,
    matricula: 2519,
    nome: 'Murilo Vidal',
  },
  {
    rodada: 4,
    grupo: 26,
    matricula: 2440,
    nome: 'Natália Grein Silva',
  },
  {
    rodada: 4,
    grupo: 26,
    matricula: 2505,
    nome: 'André Schueda Menezes',
  },
  {
    rodada: 4,
    grupo: 26,
    matricula: 2455,
    nome: 'Fabiana Martins Budel',
  },
  {
    rodada: 4,
    grupo: 27,
    matricula: 2356,
    nome: 'Ana Paula De Souza Marques',
  },
  {
    rodada: 4,
    grupo: 27,
    matricula: 2432,
    nome: 'Rafaela Angelon',
  },
  {
    rodada: 4,
    grupo: 27,
    matricula: 2351,
    nome: 'Rogério Bayer Ghizi',
  },
  {
    rodada: 4,
    grupo: 27,
    matricula: 2510,
    nome: 'Julio Teixeira Bojan',
  },
  {
    rodada: 4,
    grupo: 28,
    matricula: 2491,
    nome: 'Alison Hudson De Souza',
  },
  {
    rodada: 4,
    grupo: 28,
    matricula: 2393,
    nome: 'João Pedro Picolo',
  },
  {
    rodada: 4,
    grupo: 28,
    matricula: 2391,
    nome: 'Lígia Naomi Nakase',
  },
  {
    rodada: 4,
    grupo: 28,
    matricula: 2479,
    nome: 'Alis Eugenio Frentzel',
  },
  {
    rodada: 4,
    grupo: 29,
    matricula: 2349,
    nome: 'Rafael Matheus Chaves Silveira',
  },
  {
    rodada: 4,
    grupo: 29,
    matricula: 2474,
    nome: 'Sali Goretti Stocco',
  },
  {
    rodada: 4,
    grupo: 29,
    matricula: 2490,
    nome: 'Gustavo Esteves Fernandes',
  },
  {
    rodada: 4,
    grupo: 29,
    matricula: 2433,
    nome: 'Ingrid Vitória Giese',
  },
  {
    rodada: 4,
    grupo: 30,
    matricula: 2468,
    nome: 'Márcio José Gurka Júnior',
  },
  {
    rodada: 4,
    grupo: 30,
    matricula: 2426,
    nome: 'Matheus Teixeira Souza',
  },
  {
    rodada: 4,
    grupo: 30,
    matricula: 2441,
    nome: 'Letícia Vallejo Zaranski',
  },
  {
    rodada: 4,
    grupo: 30,
    matricula: 2366,
    nome: 'Maria Teresa Kravetz Andrioli',
  },
  {
    rodada: 4,
    grupo: 31,
    matricula: 2438,
    nome: 'Yasmin Mayer',
  },
  {
    rodada: 4,
    grupo: 31,
    matricula: 2350,
    nome: 'Alessandro Maciel Schmidt',
  },
  {
    rodada: 4,
    grupo: 31,
    matricula: 2411,
    nome: 'João Vitor Moreira',
  },
  {
    rodada: 4,
    grupo: 31,
    matricula: 2460,
    nome: 'Tacila Fernanda Carneiro Evangelista',
  },
  {
    rodada: 4,
    grupo: 32,
    matricula: 2381,
    nome: 'Melissa Fernanda Rodrigues Siqueira',
  },
  {
    rodada: 4,
    grupo: 32,
    matricula: 2405,
    nome: 'Bruna Martins De Oliveira',
  },
  {
    rodada: 4,
    grupo: 32,
    matricula: 2407,
    nome: 'Bruno Siedekum Thuma',
  },
  {
    rodada: 4,
    grupo: 32,
    matricula: 2348,
    nome: 'Bernardo Augusto Monteiro De Oliveira Klingelfus',
  },
  {
    rodada: 4,
    grupo: 33,
    matricula: 2513,
    nome: 'Pedro Henrique Cordeiro Soares',
  },
  {
    rodada: 4,
    grupo: 33,
    matricula: 2379,
    nome: 'Cássia Megumi Fuku Oban',
  },
  {
    rodada: 4,
    grupo: 33,
    matricula: 2499,
    nome: 'Neidivaldo Dias Da Silva Junior',
  },
  {
    rodada: 4,
    grupo: 33,
    matricula: 2355,
    nome: 'Luana Mara Dalla Costa',
  },
  {
    rodada: 4,
    grupo: 34,
    matricula: 2428,
    nome: 'Iara Curcio Fadel',
  },
  {
    rodada: 4,
    grupo: 34,
    matricula: 2373,
    nome: 'Ianca Polizelo',
  },
  {
    rodada: 4,
    grupo: 34,
    matricula: 2409,
    nome: 'Alan Renato Bunese',
  },
  {
    rodada: 4,
    grupo: 34,
    matricula: 2506,
    nome: 'Vinícius Couto Tasso',
  },
  {
    rodada: 4,
    grupo: 35,
    matricula: 2399,
    nome: 'Raul Gomes Pimentel De Almeida',
  },
  {
    rodada: 4,
    grupo: 35,
    matricula: 2410,
    nome: 'Milena Almeida De Menezes Caldas',
  },
  {
    rodada: 4,
    grupo: 35,
    matricula: 2408,
    nome: 'Gabriele Batista Do Nascimento',
  },
  {
    rodada: 4,
    grupo: 35,
    matricula: 2508,
    nome: 'Victor Henrique De Moura Netto',
  },
  {
    rodada: 4,
    grupo: 36,
    matricula: 2398,
    nome: 'Marlon Griebeler Da Hora',
  },
  {
    rodada: 4,
    grupo: 36,
    matricula: 2514,
    nome: 'Pedro Henrique Schisler Squisati',
  },
  {
    rodada: 4,
    grupo: 36,
    matricula: 2467,
    nome: 'Flavia Lombardi Maceira',
  },
  {
    rodada: 4,
    grupo: 36,
    matricula: 2435,
    nome: 'Suzy Shiori Sakano',
  },
  {
    rodada: 4,
    grupo: 37,
    matricula: 2358,
    nome: 'Hamilton Wanderson Fortes De Menezes',
  },
  {
    rodada: 4,
    grupo: 37,
    matricula: 2374,
    nome: 'Lucas Otavio Mariano Pinheiro Oro',
  },
  {
    rodada: 4,
    grupo: 37,
    matricula: 2461,
    nome: 'Kimberlly Hapuque Da Silva Brito',
  },
  {
    rodada: 4,
    grupo: 37,
    matricula: 2453,
    nome: 'Ana Paula Vieira Roviero',
  },
  {
    rodada: 4,
    grupo: 38,
    matricula: 2480,
    nome: 'Alexandra Dos Santos Gropp',
  },
  {
    rodada: 4,
    grupo: 38,
    matricula: 2414,
    nome: 'Marco Antônio Barbosa Zulian',
  },
  {
    rodada: 4,
    grupo: 38,
    matricula: 2413,
    nome: 'Letícia Camargo De Sá Silva',
  },
  {
    rodada: 4,
    grupo: 38,
    matricula: 2488,
    nome: 'Paulo Tadashi Tokikawa',
  },
  {
    rodada: 4,
    grupo: 39,
    matricula: 2378,
    nome: 'Sthefanny Ferreira Gonzaga',
  },
  {
    rodada: 4,
    grupo: 39,
    matricula: 2504,
    nome: 'André Luís Arns Guimarães',
  },
  {
    rodada: 4,
    grupo: 39,
    matricula: 2359,
    nome: 'Alessandra Fernandes Lacerda',
  },
  {
    rodada: 4,
    grupo: 39,
    matricula: 2425,
    nome: 'Guilherme Morais Lopes Dos Santos',
  },
  {
    rodada: 4,
    grupo: 40,
    matricula: 2376,
    nome: 'Samuel Eberhardt',
  },
  {
    rodada: 4,
    grupo: 40,
    matricula: 2482,
    nome: 'Guilherme Barbosa Candido',
  },
  {
    rodada: 4,
    grupo: 40,
    matricula: 2442,
    nome: 'Isadora Rossetto Nogueira Drummond',
  },
  {
    rodada: 4,
    grupo: 40,
    matricula: 2458,
    nome: 'Stefany Jardim Rodrigues',
  },
  {
    rodada: 4,
    grupo: 41,
    matricula: 2450,
    nome: 'Henrique Castro Santos',
  },
  {
    rodada: 4,
    grupo: 41,
    matricula: 2443,
    nome: 'Natalia Seixas Dias',
  },
  {
    rodada: 4,
    grupo: 41,
    matricula: 2404,
    nome: 'Eduardo Cristiano Franco',
  },
  {
    rodada: 4,
    grupo: 41,
    matricula: 2430,
    nome: 'Larissa Paschoalin',
  },
  {
    rodada: 4,
    grupo: 42,
    matricula: 2353,
    nome: 'Alex Freitas Soares',
  },
  {
    rodada: 4,
    grupo: 42,
    matricula: 2419,
    nome: 'Marina De Domenico Salioni Dubuc',
  },
  {
    rodada: 4,
    grupo: 42,
    matricula: 2420,
    nome: 'Mônica Falat Reva Dell Agnolo',
  },
  {
    rodada: 4,
    grupo: 42,
    matricula: 2485,
    nome: 'Gabriel Puppi Gozzo',
  },
  {
    rodada: 4,
    grupo: 43,
    matricula: 2521,
    nome: 'Bruno Padovan Soares De Souza',
  },
  {
    rodada: 4,
    grupo: 43,
    matricula: 2469,
    nome: 'Lucas Yoshio Nakano',
  },
  {
    rodada: 4,
    grupo: 43,
    matricula: 2445,
    nome: 'Matheus Dos Santos Pedrozo De Lima',
  },
  {
    rodada: 4,
    grupo: 43,
    matricula: 2360,
    nome: 'Mario Morais Neto',
  },
  {
    rodada: 4,
    grupo: 44,
    matricula: 2512,
    nome: 'Pablo Enrique Harbar Penas',
  },
  {
    rodada: 4,
    grupo: 44,
    matricula: 2375,
    nome: 'Jonathas Andrade Torquato',
  },
  {
    rodada: 4,
    grupo: 44,
    matricula: 2451,
    nome: 'Enzo Trevisan Topanotti',
  },
  {
    rodada: 4,
    grupo: 44,
    matricula: 2361,
    nome: 'Leonardo José Zanotti',
  },
  {
    rodada: 4,
    grupo: 45,
    matricula: 2497,
    nome: 'Pietro Ricardo Schoch Alves',
  },
  {
    rodada: 4,
    grupo: 45,
    matricula: 2489,
    nome: 'Eduardo Batistel Zaniol',
  },
  {
    rodada: 4,
    grupo: 45,
    matricula: 2492,
    nome: 'Luiz Siqueira',
  },
  {
    rodada: 4,
    grupo: 45,
    matricula: 2362,
    nome: 'Gustavo Monkolski Tatarem',
  },
];

export const criarAtividades = (service: AtividadeService) => {
  const equipesMap: Map<number, Map<number, Equipe>> = new Map();
  importedData.forEach(data => {
    if (!equipesMap.get(data.rodada)) {
      equipesMap.set(data.rodada, new Map());
    }

    if (!equipesMap.get(data.rodada).get(data.grupo)) {
      equipesMap.get(data.rodada).set(data.grupo, { entregue: false, integrantes: [] });
    }

    equipesMap.get(data.rodada).get(data.grupo).integrantes.push(data.nome);
  });

  const novaAtividade: Atividade = {
    ativa: false,
    dataHoraInicio: '2020-10-31T08:30:00-0300',
    dataHoraFim: '2020-10-31T10:30:00-0300',
    equipes: [],
    linkEntrega: '',
  };

  const atividadesMap: Map<number, Atividade> = new Map();
  importedData.forEach(data => {
    if (!atividadesMap.get(data.rodada)) {
      atividadesMap.set(data.rodada, {
        ...novaAtividade,
        nome: `Atividade ${data.rodada + 1}`,
        equipes: Array.from(equipesMap.get(data.rodada).values()),
      });
    }
  });

  const atividades = Array.from(atividadesMap.values());

  atividades.forEach(atividade => service.add(atividade));

  console.log(Array.from(equipesMap.values()).map(a => Array.from(a.values())));
};
